import ROOT
import numpy as n

ROOT.gROOT.SetBatch(True)
ROOT.gStyle.SetOptStat(False);


tf = ROOT.TFile("../src/merged10x.root")

# TProfiles
p_pt_EA = tf.Get("p_pt_EA")
p_pt_dB = tf.Get("p_pt_dB")
p_npv_EA = tf.Get("p_npv_EA")
p_npv_dB = tf.Get("p_npv_dB")
p_npv_rhos_all = tf.Get("p_npv_rho_all")
p_npv_rhos_ctr = tf.Get("p_npv_rho_ctr")

h_npv_over_EA = tf.Get("h_npv_over_EA")
h_npv_over_dB = tf.Get("h_npv_over_dB")

########
# Mini #
########

h_all_rhos_ctr = tf.Get("h_all_rhos_ctr")

h_all_EAs = tf.Get("h_all_EAs")

h_median_EA = tf.Get("h_median_EA")
h_median_dB = tf.Get("h_median_dB")

h_all_EAcorrs = tf.Get("h_all_EAcorrs")
h_all_dBcorrs = tf.Get("h_all_dBcorrs")

h_diffCorr_low_bar = tf.Get("h_diffCorr_low_bar")
h_diffCorr_med_bar = tf.Get("h_diffCorr_med_bar")
h_diffCorr_high_bar = tf.Get("h_diffCorr_high_bar")
h_diffCorr_low_cap = tf.Get("h_diffCorr_low_cap")
h_diffCorr_med_cap = tf.Get("h_diffCorr_med_cap")
h_diffCorr_high_cap = tf.Get("h_diffCorr_high_cap")

h_all_EAs_rel = tf.Get("h_all_EAs")

h_median_EA_rel = tf.Get("h_median_EA_rel")
h_median_dB_rel = tf.Get("h_median_dB_rel")

h_all_EAcorrs_rel = tf.Get("h_all_EAcorrs_rel")
h_all_dBcorrs_rel = tf.Get("h_all_dBcorrs_rel")

h_diffCorr_low_bar_rel = tf.Get("h_diffCorr_low_bar_rel")
h_diffCorr_med_bar_rel = tf.Get("h_diffCorr_med_bar_rel")
h_diffCorr_high_bar_rel = tf.Get("h_diffCorr_high_bar_rel")
h_diffCorr_low_cap_rel = tf.Get("h_diffCorr_low_cap_rel")
h_diffCorr_med_cap_rel = tf.Get("h_diffCorr_med_cap_rel")
h_diffCorr_high_cap_rel = tf.Get("h_diffCorr_high_cap_rel")

h_neut_low_bar = tf.Get("h_neut_low_bar")
h_neut_low_cap = tf.Get("h_neut_low_cap")
h_neut_med_bar = tf.Get("h_neut_med_bar")
h_neut_med_cap = tf.Get("h_neut_med_cap")
h_neut_high_bar = tf.Get("h_neut_high_bar")
h_neut_high_cap = tf.Get("h_neut_high_cap")

h_neut_low_bar_rel = tf.Get("h_neut_low_bar_rel")
h_neut_low_cap_rel = tf.Get("h_neut_low_cap_rel")
h_neut_med_bar_rel = tf.Get("h_neut_med_bar_rel")
h_neut_med_cap_rel = tf.Get("h_neut_med_cap_rel")
h_neut_high_bar_rel = tf.Get("h_neut_high_bar_rel")
h_neut_high_cap_rel = tf.Get("h_neut_high_cap_rel")

h_neut_soft = tf.Get("h_neut_soft")
h_neut_med = tf.Get("h_neut_med")
h_neut_hard = tf.Get("h_neut_hard")

h_neut_soft_rel = tf.Get("h_neut_soft_rel")
h_neut_med_rel = tf.Get("h_neut_med_rel")
h_neut_hard_rel = tf.Get("h_neut_hard_rel")

############
# Standard #
############

h_all_rhos_all = tf.Get("h_all_rhos_all")

h_all_EAs_st = tf.Get("h_all_EAs_st")

h_median_EA_st = tf.Get("h_median_EA_st")
h_median_dB_st = tf.Get("h_median_dB_st")

h_all_EAcorrs_st = tf.Get("h_all_EAcorrs_st")
h_all_dBcorrs_st = tf.Get("h_all_dBcorrs_st")

h_diffCorr_low_bar_st = tf.Get("h_diffCorr_low_bar_st")
h_diffCorr_med_bar_st = tf.Get("h_diffCorr_med_bar_st")
h_diffCorr_high_bar_st = tf.Get("h_diffCorr_high_bar_st")
h_diffCorr_low_cap_st = tf.Get("h_diffCorr_low_cap_st")
h_diffCorr_med_cap_st = tf.Get("h_diffCorr_med_cap_st")
h_diffCorr_high_cap_st = tf.Get("h_diffCorr_high_cap_st")

h_all_EAs_rel_st = tf.Get("h_all_EAs_st")

h_median_EA_rel_st = tf.Get("h_median_EA_rel_st")
h_median_dB_rel_st = tf.Get("h_median_dB_rel_st")

h_all_EAcorrs_rel_st = tf.Get("h_all_EAcorrs_rel_st")
h_all_dBcorrs_rel_st = tf.Get("h_all_dBcorrs_rel_st")

h_diffCorr_low_bar_rel_st = tf.Get("h_diffCorr_low_bar_rel_st")
h_diffCorr_med_bar_rel_st = tf.Get("h_diffCorr_med_bar_rel_st")
h_diffCorr_high_bar_rel_st = tf.Get("h_diffCorr_high_bar_rel_st")
h_diffCorr_low_cap_rel_st = tf.Get("h_diffCorr_low_cap_rel_st")
h_diffCorr_med_cap_rel_st = tf.Get("h_diffCorr_med_cap_rel_st")
h_diffCorr_high_cap_rel_st = tf.Get("h_diffCorr_high_cap_rel_st")

h_dB_vs_EA_low_bar_rel_st = tf.Get("h_dB_vs_EA_low_bar_rel_st")
h_dB_vs_EA_low_cap_rel_st = tf.Get("h_dB_vs_EA_low_cap_rel_st")
h_dB_vs_EA_med_bar_rel_st = tf.Get("h_dB_vs_EA_med_bar_rel_st")
h_dB_vs_EA_med_cap_rel_st = tf.Get("h_dB_vs_EA_med_cap_rel_st")
h_dB_vs_EA_high_bar_rel_st = tf.Get("h_dB_vs_EA_high_bar_rel_st")
h_dB_vs_EA_high_cap_rel_st = tf.Get("h_dB_vs_EA_high_cap_rel_st")

h_neut_low_bar_st = tf.Get("h_neut_low_bar_st")
h_neut_low_cap_st = tf.Get("h_neut_low_cap_st")
h_neut_med_bar_st = tf.Get("h_neut_med_bar_st")
h_neut_med_cap_st = tf.Get("h_neut_med_cap_st")
h_neut_high_bar_st = tf.Get("h_neut_high_bar_st")
h_neut_high_cap_st = tf.Get("h_neut_high_cap_st")

h_neut_low_bar_rel_st = tf.Get("h_neut_low_bar_rel_st")
h_neut_low_cap_rel_st = tf.Get("h_neut_low_cap_rel_st")
h_neut_med_bar_rel_st = tf.Get("h_neut_med_bar_rel_st")
h_neut_med_cap_rel_st = tf.Get("h_neut_med_cap_rel_st")
h_neut_high_bar_rel_st = tf.Get("h_neut_high_bar_rel_st")
h_neut_high_cap_rel_st = tf.Get("h_neut_high_cap_rel_st")

h_neut_soft_st = tf.Get("h_neut_soft_st")
h_neut_med_st = tf.Get("h_neut_med_st")
h_neut_hard_st = tf.Get("h_neut_hard_st")

h_neut_soft_rel_st = tf.Get("h_neut_soft_rel_st")
h_neut_med_rel_st = tf.Get("h_neut_med_rel_st")
h_neut_hard_rel_st = tf.Get("h_neut_hard_rel_st")


integral = int(h_all_EAs.Integral())
h_all_EAs.SetTitle("All Mini Effective Areas ("+str(integral)+" muons);Effective Area;Fraction")
h_all_EAs.Scale(1./integral)

h_median_dB.SetTitle("Median Corrections as Function of N_{PV};N_{PV};Median Absolute MiniIso Correction (GeV)")
h_median_dB.SetLineColor(ROOT.kRed)
h_median_dB.GetYaxis().SetTitleOffset(1.6)

integral = int(h_all_EAcorrs.Integral())
h_all_EAcorrs.SetTitle("All MiniIso Effective Area Corrections ("+str(integral)+" muons);Absolute Effective Area Correction (GeV);Fraction")
h_all_EAcorrs.Scale(1./integral)
integral = int(h_all_dBcorrs.Integral())
h_all_dBcorrs.SetTitle("All MiniIso #Delta#beta Corrections ("+str(integral)+" muons);Absolute #Delta#beta Correction (GeV);Fraction")
h_all_dBcorrs.Scale(1./integral)

integral = int(h_diffCorr_low_bar.Integral())
h_diffCorr_low_bar.SetTitle("MiniIso #Delta#beta - Effective Area, |#eta| < 1.4, N_{PV} < 20 ("+str(integral)+" muons);#Delta#beta-EA (GeV);Fraction")
h_diffCorr_low_bar.Scale(1./integral)
h_diffCorr_low_bar.GetYaxis().SetTitleOffset(1.6)
integral = int(h_diffCorr_low_cap.Integral())
h_diffCorr_low_cap.SetTitle("MiniIso #Delta#beta - Effective Area, 1.4 < |#eta| < 2.4, N_{PV} < 20 ("+str(integral)+" muons);#Delta#beta-EA (GeV);Fraction")
h_diffCorr_low_cap.Scale(1./integral)
h_diffCorr_low_cap.GetYaxis().SetTitleOffset(1.6)
integral = int(h_diffCorr_med_bar.Integral())
h_diffCorr_med_bar.SetTitle("MiniIso #Delta#beta - Effective Area, |#eta| < 1.4, 20 <= N_{PV} < 40 ("+str(integral)+" muons);#Delta#beta-EA (GeV);Fraction")
h_diffCorr_med_bar.Scale(1./integral)
h_diffCorr_med_bar.GetYaxis().SetTitleOffset(1.6)
integral = int(h_diffCorr_med_cap.Integral())
h_diffCorr_med_cap.SetTitle("MiniIso #Delta#beta - Effective Area, 1.4 < |#eta| < 2.4, 20 <= N_{PV} < 40 ("+str(integral)+" muons);#Delta#beta-EA (GeV);Fraction")
h_diffCorr_med_cap.Scale(1./integral)
h_diffCorr_med_cap.GetYaxis().SetTitleOffset(1.6)
integral = int(h_diffCorr_high_bar.Integral())
h_diffCorr_high_bar.SetTitle("MiniIso #Delta#beta - Effective Area, |#eta| < 1.4, N_{PV} > 40 ("+str(integral)+" muons);#Delta#beta-EA (GeV);Fraction")
h_diffCorr_high_bar.Scale(1./integral)
h_diffCorr_high_bar.GetYaxis().SetTitleOffset(1.6)
integral = int(h_diffCorr_high_cap.Integral())
h_diffCorr_high_cap.SetTitle("MiniIso #Delta#beta - Effective Area, 1.4 < |#eta| < 2.4, N_{PV} > 40 ("+str(integral)+" muons);#Delta#beta-EA (GeV);Fraction")
h_diffCorr_high_cap.Scale(1./integral)
h_diffCorr_high_cap.GetYaxis().SetTitleOffset(1.6)

integral = int(h_neut_low_bar.Integral())
h_neut_low_bar.SetTitle("Mini Neutral Isolation, |#eta| < 1.4, N_{PV} < 20 ("+str(integral)+" muons);Uncorrected Neutral MiniIso (GeV);Fraction")
h_neut_low_bar.Scale(1./integral)
h_neut_low_bar.GetYaxis().SetTitleOffset(1.6)
integral = int(h_neut_low_cap.Integral())
h_neut_low_cap.SetTitle("Mini Neutral Isolation, 1.4 < |#eta| < 2.4, N_{PV} < 20 ("+str(integral)+" muons);Uncorrected Neutral MiniIso (GeV);Fraction")
h_neut_low_cap.Scale(1./integral)
h_neut_low_cap.GetYaxis().SetTitleOffset(1.6)
integral = int(h_neut_med_bar.Integral())
h_neut_med_bar.SetTitle("Mini Neutral Isolation, |#eta| < 1.4, 20 <= N_{PV} < 40 ("+str(integral)+" muons);Uncorrected Neutral MiniIso (GeV);Fraction")
h_neut_med_bar.Scale(1./integral)
h_neut_med_bar.GetYaxis().SetTitleOffset(1.6)
integral = int(h_neut_med_cap.Integral())
h_neut_med_cap.SetTitle("Mini Neutral Isolation, 1.4 < |#eta| < 2.4, 20 <= N_{PV} < 40 ("+str(integral)+" muons);Uncorrected Neutral MiniIso (GeV);Fraction")
h_neut_med_cap.Scale(1./integral)
h_neut_med_cap.GetYaxis().SetTitleOffset(1.6)
integral = int(h_neut_high_bar.Integral())
h_neut_high_bar.SetTitle("Mini Neutral Isolation, |#eta| < 1.4, N_{PV} > 40 ("+str(integral)+" muons);Uncorrected Neutral MiniIso (GeV);Fraction")
h_neut_high_bar.Scale(1./integral)
h_neut_high_bar.GetYaxis().SetTitleOffset(1.6)
integral = int(h_neut_high_cap.Integral())
h_neut_high_cap.SetTitle("Mini Neutral Isolation, 1.4 < |#eta| < 2.4, N_{PV} > 40 ("+str(integral)+" muons);Uncorrected Neutral MiniIso (GeV);Fraction")
h_neut_high_cap.Scale(1./integral)
h_neut_high_cap.GetYaxis().SetTitleOffset(1.6)

integral = int(h_neut_soft.Integral())
h_neut_soft.SetTitle("Mini Neutral Isolation, p_{T} < 50 GeV ("+str(integral)+" muons);Uncorrected Neutral MiniIso (GeV);Fraction")
h_neut_soft.Scale(1./integral)
h_neut_soft.GetYaxis().SetTitleOffset(1.6)
integral = int(h_neut_med.Integral())
h_neut_med.SetTitle("Mini Neutral Isolation, 50 < p_{T} < 200 GeV ("+str(integral)+" muons);Uncorrected Neutral MiniIso (GeV);Fraction")
h_neut_med.Scale(1./integral)
h_neut_med.GetYaxis().SetTitleOffset(1.6)
integral = int(h_neut_hard.Integral())
h_neut_hard.SetTitle("Mini Neutral Isolation, p_{T} > 200 GeV ("+str(integral)+" muons);Uncorrected Neutral MiniIso (GeV);Fraction")
h_neut_hard.Scale(1./integral)
h_neut_hard.GetYaxis().SetTitleOffset(1.6)

# Standard

h_median_dB_st.SetTitle("Median Corrections as Function of N_{PV};N_{PV};Median Absolute #DeltaR = 0.3 Iso Correction (GeV)")
h_median_dB_st.SetLineColor(ROOT.kRed)
h_median_dB_st.GetYaxis().SetTitleOffset(1.6)

integral = int(h_all_EAcorrs_st.Integral())
h_all_EAcorrs_st.SetTitle("All #DeltaR = 0.3 Iso Effective Area Corrections ("+str(integral)+" muons);Effective Area Correction (GeV);Fraction")
h_all_EAcorrs_st.Scale(1./integral)
integral = int(h_all_dBcorrs_st.Integral())
h_all_dBcorrs_st.SetTitle("All #DeltaR = 0.3 Iso #Delta#beta Corrections ("+str(integral)+" muons);#Delta#beta Correction (GeV);Fraction")
h_all_dBcorrs_st.Scale(1./integral)

integral = int(h_diffCorr_low_bar_st.Integral())
h_diffCorr_low_bar_st.SetTitle("#DeltaR = 0.3 Iso #Delta#beta - Effective Area, |#eta| < 1.4, N_{PV} < 20 ("+str(integral)+" muons);#Delta#beta-EA (GeV);Fraction")
h_diffCorr_low_bar_st.Scale(1./integral)
h_diffCorr_low_bar_st.GetYaxis().SetTitleOffset(1.6)
integral = int(h_diffCorr_low_cap_st.Integral())
h_diffCorr_low_cap_st.SetTitle("#DeltaR = 0.3 Iso #Delta#beta - Effective Area, 1.4 < |#eta| < 2.4, N_{PV} < 20 ("+str(integral)+" muons);#Delta#beta-EA (GeV);Fraction")
h_diffCorr_low_cap_st.Scale(1./integral)
h_diffCorr_low_cap_st.GetYaxis().SetTitleOffset(1.6)
integral = int(h_diffCorr_med_bar_st.Integral())
h_diffCorr_med_bar_st.SetTitle("#DeltaR = 0.3 Iso #Delta#beta - Effective Area, |#eta| < 1.4, 20 <= N_{PV} < 40 ("+str(integral)+" muons);#Delta#beta-EA (GeV);Fraction")
h_diffCorr_med_bar_st.Scale(1./integral)
h_diffCorr_med_bar_st.GetYaxis().SetTitleOffset(1.6)
integral = int(h_diffCorr_med_cap_st.Integral())
h_diffCorr_med_cap_st.SetTitle("#DeltaR = 0.3 Iso #Delta#beta - Effective Area, 1.4 < |#eta| < 2.4, 20 <= N_{PV} < 40 ("+str(integral)+" muons);#Delta#beta-EA (GeV);Fraction")
h_diffCorr_med_cap_st.Scale(1./integral)
h_diffCorr_med_cap_st.GetYaxis().SetTitleOffset(1.6)
integral = int(h_diffCorr_high_bar_st.Integral())
h_diffCorr_high_bar_st.SetTitle("#DeltaR = 0.3 Iso #Delta#beta - Effective Area, |#eta| < 1.4, N_{PV} > 40 ("+str(integral)+" muons);#Delta#beta-EA (GeV);Fraction")
h_diffCorr_high_bar_st.Scale(1./integral)
h_diffCorr_high_bar_st.GetYaxis().SetTitleOffset(1.6)
integral = int(h_diffCorr_high_cap_st.Integral())
h_diffCorr_high_cap_st.SetTitle("#DeltaR = 0.3 Iso #Delta#beta - Effective Area, 1.4 < |#eta| < 2.4, N_{PV} > 40 ("+str(integral)+" muons);#Delta#beta-EA (GeV);Fraction")
h_diffCorr_high_cap_st.Scale(1./integral)
h_diffCorr_high_cap_st.GetYaxis().SetTitleOffset(1.6)

integral = int(h_neut_low_bar_st.Integral())
h_neut_low_bar_st.SetTitle("#DeltaR = 0.3 Neutral Isolation, |#eta| < 1.4, N_{PV} < 20 ("+str(integral)+" muons);Uncorrected Neutral #DeltaR = 0.3 Isolation (GeV);Fraction")
h_neut_low_bar_st.Scale(1./integral)
h_neut_low_bar_st.GetYaxis().SetTitleOffset(1.6)
integral = int(h_neut_low_cap_st.Integral())
h_neut_low_cap_st.SetTitle("#DeltaR = 0.3 Neutral Isolation, 1.4 < |#eta| < 2.4, N_{PV} < 20 ("+str(integral)+" muons);Uncorrected Neutral #DeltaR = 0.3 Isolation (GeV);Fraction")
h_neut_low_cap_st.Scale(1./integral)
h_neut_low_cap_st.GetYaxis().SetTitleOffset(1.6)
integral = int(h_neut_med_bar_st.Integral())
h_neut_med_bar_st.SetTitle("#DeltaR = 0.3 Neutral Isolation, |#eta| < 1.4, 20 <= N_{PV} < 40 ("+str(integral)+" muons);Uncorrected Neutral #DeltaR = 0.3 Isolation (GeV);Fraction")
h_neut_med_bar_st.Scale(1./integral)
h_neut_med_bar_st.GetYaxis().SetTitleOffset(1.6)
integral = int(h_neut_med_cap_st.Integral())
h_neut_med_cap_st.SetTitle("#DeltaR = 0.3 Neutral Isolation, 1.4 < |#eta| < 2.4, 20 <= N_{PV} < 40 ("+str(integral)+" muons);Uncorrected Neutral #DeltaR = 0.3 Isolation (GeV);Fraction")
h_neut_med_cap_st.Scale(1./integral)
h_neut_med_cap_st.GetYaxis().SetTitleOffset(1.6)
integral = int(h_neut_high_bar_st.Integral())
h_neut_high_bar_st.SetTitle("#DeltaR = 0.3 Neutral Isolation, |#eta| < 1.4, N_{PV} > 40 ("+str(integral)+" muons);Uncorrected Neutral #DeltaR = 0.3 Isolation (GeV);Fraction")
h_neut_high_bar_st.Scale(1./integral)
h_neut_high_bar_st.GetYaxis().SetTitleOffset(1.6)
integral = int(h_neut_high_cap_st.Integral())
h_neut_high_cap_st.SetTitle("#DeltaR = 0.3 Neutral Isolation, 1.4 < |#eta| < 2.4, N_{PV} > 40 ("+str(integral)+" muons);Uncorrected Neutral #DeltaR = 0.3 Isolation (GeV);Fraction")
h_neut_high_cap_st.Scale(1./integral)
h_neut_high_cap_st.GetYaxis().SetTitleOffset(1.6)

integral = int(h_neut_soft_st.Integral())
h_neut_soft_st.SetTitle("#DeltaR = 0.3 Neutral Isolation, p_{T} < 50 GeV ("+str(integral)+" muons);Uncorrected Neutral #DeltaR = 0.3 Isolation (GeV);Fraction")
h_neut_soft_st.Scale(1./integral)
h_neut_soft_st.GetYaxis().SetTitleOffset(1.6)
integral = int(h_neut_med_st.Integral())
h_neut_med_st.SetTitle("#DeltaR = 0.3 Neutral Isolation, 50 < p_{T} < 200 GeV ("+str(integral)+" muons);Uncorrected Neutral #DeltaR = 0.3 Isolation (GeV);Fraction")
h_neut_med_st.Scale(1./integral)
h_neut_med_st.GetYaxis().SetTitleOffset(1.6)
integral = int(h_neut_hard_st.Integral())
h_neut_hard_st.SetTitle("#DeltaR = 0.3 Neutral Isolation, p_{T} > 200 GeV ("+str(integral)+" muons);Uncorrected Neutral #DeltaR = 0.3 Isolation (GeV);Fraction")
h_neut_hard_st.Scale(1./integral)
h_neut_hard_st.GetYaxis().SetTitleOffset(1.6)


############
# Relative #
############


h_median_dB_rel.SetTitle("Median Corrections as Function of N_{PV};N_{PV};Median Relative MiniIso Correction")
h_median_dB_rel.SetLineColor(ROOT.kRed)
h_median_dB_rel.GetYaxis().SetTitleOffset(1.6)

integral = int(h_all_EAcorrs_rel.Integral())
h_all_EAcorrs_rel.SetTitle("All Relative MiniIso Effective Area Corrections ("+str(integral)+" muons);Effective Area Correction;Fraction")
h_all_EAcorrs_rel.Scale(1./integral)
integral = int(h_all_dBcorrs_rel.Integral())
h_all_dBcorrs_rel.SetTitle("All Relative MiniIso #Delta#beta Corrections ("+str(integral)+" muons);#Delta#beta Correction;Fraction")
h_all_dBcorrs_rel.Scale(1./integral)

integral = int(h_diffCorr_low_bar_rel.Integral())
h_diffCorr_low_bar_rel.SetTitle("Relative MiniIso #Delta#beta - Effective Area, |#eta| < 1.4, N_{PV} < 20 ("+str(integral)+" muons);#Delta#beta-EA;Fraction")
h_diffCorr_low_bar_rel.Scale(1./integral)
h_diffCorr_low_bar_rel.GetYaxis().SetTitleOffset(1.6)
integral = int(h_diffCorr_low_cap_rel.Integral())
h_diffCorr_low_cap_rel.SetTitle("Relative MiniIso #Delta#beta - Effective Area, 1.4 < |#eta| < 2.4, N_{PV} < 20 ("+str(integral)+" muons);#Delta#beta-EA;Fraction")
h_diffCorr_low_cap_rel.Scale(1./integral)
h_diffCorr_low_cap_rel.GetYaxis().SetTitleOffset(1.6)
integral = int(h_diffCorr_med_bar_rel.Integral())
h_diffCorr_med_bar_rel.SetTitle("Relative MiniIso #Delta#beta - Effective Area, |#eta| < 1.4, 20 <= N_{PV} < 40 ("+str(integral)+" muons);#Delta#beta-EA;Fraction")
h_diffCorr_med_bar_rel.Scale(1./integral)
h_diffCorr_med_bar_rel.GetYaxis().SetTitleOffset(1.6)
integral = int(h_diffCorr_med_cap_rel.Integral())
h_diffCorr_med_cap_rel.SetTitle("Relative MiniIso #Delta#beta - Effective Area, 1.4 < |#eta| < 2.4, 20 <= N_{PV} < 40 ("+str(integral)+" muons);#Delta#beta-EA;Fraction")
h_diffCorr_med_cap_rel.Scale(1./integral)
h_diffCorr_med_cap_rel.GetYaxis().SetTitleOffset(1.6)
integral = int(h_diffCorr_high_bar_rel.Integral())
h_diffCorr_high_bar_rel.SetTitle("Relative MiniIso #Delta#beta - Effective Area, |#eta| < 1.4, N_{PV} > 40 ("+str(integral)+" muons);#Delta#beta-EA;Fraction")
h_diffCorr_high_bar_rel.Scale(1./integral)
h_diffCorr_high_bar_rel.GetYaxis().SetTitleOffset(1.6)
integral = int(h_diffCorr_high_cap_rel.Integral())
h_diffCorr_high_cap_rel.SetTitle("Relative MiniIso #Delta#beta - Effective Area, 1.4 < |#eta| < 2.4, N_{PV} > 40 ("+str(integral)+" muons);#Delta#beta-EA;Fraction")
h_diffCorr_high_cap_rel.Scale(1./integral)
h_diffCorr_high_cap_rel.GetYaxis().SetTitleOffset(1.6)

integral = int(h_neut_low_bar_rel.Integral())
h_neut_low_bar_rel.SetTitle("Relative Mini Neutral Isolation, |#eta| < 1.4, N_{PV} < 20 ("+str(integral)+" muons);Uncorrected Neutral Mini Isolation;Fraction")
h_neut_low_bar_rel.Scale(1./integral)
h_neut_low_bar_rel.GetYaxis().SetTitleOffset(1.6)
integral = int(h_neut_low_cap_rel.Integral())
h_neut_low_cap_rel.SetTitle("Relative Mini Neutral Isolation, 1.4 < |#eta| < 2.4, N_{PV} < 20 ("+str(integral)+" muons);Uncorrected Neutral Mini Isolation;Fraction")
h_neut_low_cap_rel.Scale(1./integral)
h_neut_low_cap_rel.GetYaxis().SetTitleOffset(1.6)
integral = int(h_neut_med_bar_rel.Integral())
h_neut_med_bar_rel.SetTitle("Relative Mini Neutral Isolation, |#eta| < 1.4, 20 <= N_{PV} < 40 ("+str(integral)+" muons);Uncorrected Neutral Mini Isolation;Fraction")
h_neut_med_bar_rel.Scale(1./integral)
h_neut_med_bar_rel.GetYaxis().SetTitleOffset(1.6)
integral = int(h_neut_med_cap_rel.Integral())
h_neut_med_cap_rel.SetTitle("Relative Mini Neutral Isolation, 1.4 < |#eta| < 2.4, 20 <= N_{PV} < 40 ("+str(integral)+" muons);Uncorrected Neutral Mini Isolation;Fraction")
h_neut_med_cap_rel.Scale(1./integral)
h_neut_med_cap_rel.GetYaxis().SetTitleOffset(1.6)
integral = int(h_neut_high_bar_rel.Integral())
h_neut_high_bar_rel.SetTitle("Relative Mini Neutral Isolation, |#eta| < 1.4, N_{PV} > 40 ("+str(integral)+" muons);Uncorrected Neutral Mini Isolation;Fraction")
h_neut_high_bar_rel.Scale(1./integral)
h_neut_high_bar_rel.GetYaxis().SetTitleOffset(1.6)
integral = int(h_neut_high_cap_rel.Integral())
h_neut_high_cap_rel.SetTitle("Relative Mini Neutral Isolation, 1.4 < |#eta| < 2.4, N_{PV} > 40 ("+str(integral)+" muons);Uncorrected Neutral Mini Isolation;Fraction")
h_neut_high_cap_rel.Scale(1./integral)
h_neut_high_cap_rel.GetYaxis().SetTitleOffset(1.6)

integral = int(h_neut_soft_rel.Integral())
h_neut_soft_rel.SetTitle("Relative Mini Neutral Isolation, p_{T} < 50 GeV ("+str(integral)+" muons);Uncorrected Neutral Mini Isolation;Fraction")
h_neut_soft_rel.Scale(1./integral)
h_neut_soft_rel.GetYaxis().SetTitleOffset(1.6)
integral = int(h_neut_med_rel.Integral())
h_neut_med_rel.SetTitle("Relative Mini Neutral Isolation, 50 < p_{T} < 200 GeV ("+str(integral)+" muons);Uncorrected Neutral Mini Isolation;Fraction")
h_neut_med_rel.Scale(1./integral)
h_neut_med_rel.GetYaxis().SetTitleOffset(1.6)
integral = int(h_neut_hard_rel.Integral())
h_neut_hard_rel.SetTitle("Relative Mini Neutral Isolation, p_{T} > 200 GeV ("+str(integral)+" muons);Uncorrected Neutral Mini Isolation;Fraction")
h_neut_hard_rel.Scale(1./integral)
h_neut_hard_rel.GetYaxis().SetTitleOffset(1.6)

# Standard

h_median_dB_rel_st.SetTitle("Median Corrections as Function of N_{PV};N_{PV};Median Relative #DeltaR = 0.3 Iso Correction")
h_median_dB_rel_st.SetLineColor(ROOT.kRed)
h_median_dB_rel_st.GetYaxis().SetTitleOffset(1.6)

integral = int(h_all_EAcorrs_rel_st.Integral())
h_all_EAcorrs_rel_st.SetTitle("All #DeltaR = 0.3 Iso Effective Area Corrections ("+str(integral)+" muons);Effective Area Correction;Fraction")
h_all_EAcorrs_rel_st.Scale(1./integral)
integral = int(h_all_dBcorrs_rel_st.Integral())
h_all_dBcorrs_rel_st.SetTitle("All #DeltaR = 0.3 Iso #Delta#beta Corrections ("+str(integral)+" muons);#Delta#beta Correction;Fraction")
h_all_dBcorrs_rel_st.Scale(1./integral)

integral = int(h_diffCorr_low_bar_rel_st.Integral())
h_diffCorr_low_bar_rel_st.SetTitle("#DeltaR = 0.3 Iso #Delta#beta - Effective Area, |#eta| < 1.4, N_{PV} < 20 ("+str(integral)+" muons);#Delta#beta-EA;Fraction")
h_diffCorr_low_bar_rel_st.Scale(1./integral)
h_diffCorr_low_bar_rel_st.GetYaxis().SetTitleOffset(1.6)
integral = int(h_diffCorr_low_cap_rel_st.Integral())
h_diffCorr_low_cap_rel_st.SetTitle("#DeltaR = 0.3 Iso #Delta#beta - Effective Area, 1.4 < |#eta| < 2.4, N_{PV} < 20 ("+str(integral)+" muons);#Delta#beta-EA;Fraction")
h_diffCorr_low_cap_rel_st.Scale(1./integral)
h_diffCorr_low_cap_rel_st.GetYaxis().SetTitleOffset(1.6)
integral = int(h_diffCorr_med_bar_rel_st.Integral())
h_diffCorr_med_bar_rel_st.SetTitle("#DeltaR = 0.3 Iso #Delta#beta - Effective Area, |#eta| < 1.4, 20 <= N_{PV} < 40 ("+str(integral)+" muons);#Delta#beta-EA;Fraction")
h_diffCorr_med_bar_rel_st.Scale(1./integral)
h_diffCorr_med_bar_rel_st.GetYaxis().SetTitleOffset(1.6)
integral = int(h_diffCorr_med_cap_rel_st.Integral())
h_diffCorr_med_cap_rel_st.SetTitle("#DeltaR = 0.3 Iso #Delta#beta - Effective Area, 1.4 < |#eta| < 2.4, 20 <= N_{PV} < 40 ("+str(integral)+" muons);#Delta#beta-EA;Fraction")
h_diffCorr_med_cap_rel_st.Scale(1./integral)
h_diffCorr_med_cap_rel_st.GetYaxis().SetTitleOffset(1.6)
integral = int(h_diffCorr_high_bar_rel_st.Integral())
h_diffCorr_high_bar_rel_st.SetTitle("#DeltaR = 0.3 Iso #Delta#beta - Effective Area, |#eta| < 1.4, N_{PV} > 40 ("+str(integral)+" muons);#Delta#beta-EA;Fraction")
h_diffCorr_high_bar_rel_st.Scale(1./integral)
h_diffCorr_high_bar_rel_st.GetYaxis().SetTitleOffset(1.6)
integral = int(h_diffCorr_high_cap_rel_st.Integral())
h_diffCorr_high_cap_rel_st.SetTitle("#DeltaR = 0.3 Iso #Delta#beta - Effective Area, 1.4 < |#eta| < 2.4, N_{PV} > 40 ("+str(integral)+" muons);#Delta#beta-EA;Fraction")
h_diffCorr_high_cap_rel_st.Scale(1./integral)
h_diffCorr_high_cap_rel_st.GetYaxis().SetTitleOffset(1.6)

integral = int(h_neut_low_bar_rel_st.Integral())
h_neut_low_bar_rel_st.SetTitle("Relative #DeltaR = 0.3 Neutral Isolation, |#eta| < 1.4, N_{PV} < 20 ("+str(integral)+" muons);Uncorrected Neutral #DeltaR = 0.3 Isolation;Fraction")
h_neut_low_bar_rel_st.Scale(1./integral)
h_neut_low_bar_rel_st.GetYaxis().SetTitleOffset(1.6)
integral = int(h_neut_low_cap_rel_st.Integral())
h_neut_low_cap_rel_st.SetTitle("Relative #DeltaR = 0.3 Neutral Isolation, 1.4 < |#eta| < 2.4, N_{PV} < 20 ("+str(integral)+" muons);Uncorrected Neutral #DeltaR = 0.3 Isolation;Fraction")
h_neut_low_cap_rel_st.Scale(1./integral)
h_neut_low_cap_rel_st.GetYaxis().SetTitleOffset(1.6)
integral = int(h_neut_med_bar_rel_st.Integral())
h_neut_med_bar_rel_st.SetTitle("Relative #DeltaR = 0.3 Neutral Isolation, |#eta| < 1.4, 20 <= N_{PV} < 40 ("+str(integral)+" muons);Uncorrected Neutral #DeltaR = 0.3 Isolation;Fraction")
h_neut_med_bar_rel_st.Scale(1./integral)
h_neut_med_bar_rel_st.GetYaxis().SetTitleOffset(1.6)
integral = int(h_neut_med_cap_rel_st.Integral())
h_neut_med_cap_rel_st.SetTitle("Relative #DeltaR = 0.3 Neutral Isolation, 1.4 < |#eta| < 2.4, 20 <= N_{PV} < 40 ("+str(integral)+" muons);Uncorrected Neutral #DeltaR = 0.3 Isolation;Fraction")
h_neut_med_cap_rel_st.Scale(1./integral)
h_neut_med_cap_rel_st.GetYaxis().SetTitleOffset(1.6)
integral = int(h_neut_high_bar_rel_st.Integral())
h_neut_high_bar_rel_st.SetTitle("Relative #DeltaR = 0.3 Neutral Isolation, |#eta| < 1.4, N_{PV} > 40 ("+str(integral)+" muons);Uncorrected Neutral #DeltaR = 0.3 Isolation;Fraction")
h_neut_high_bar_rel_st.Scale(1./integral)
h_neut_high_bar_rel_st.GetYaxis().SetTitleOffset(1.6)
integral = int(h_neut_high_cap_rel_st.Integral())
h_neut_high_cap_rel_st.SetTitle("Relative #DeltaR = 0.3 Neutral Isolation, 1.4 < |#eta| < 2.4, N_{PV} > 40 ("+str(integral)+" muons);Uncorrected Neutral #DeltaR = 0.3 Isolation;Fraction")
h_neut_high_cap_rel_st.Scale(1./integral)
h_neut_high_cap_rel_st.GetYaxis().SetTitleOffset(1.6)

integral = int(h_neut_soft_rel_st.Integral())
h_neut_soft_rel_st.SetTitle("Relative #DeltaR = 0.3 Neutral Isolation, p_{T} < 50 GeV ("+str(integral)+" muons);Uncorrected Neutral #DeltaR = 0.3 Isolation;Fraction")
h_neut_soft_rel_st.Scale(1./integral)
h_neut_soft_rel_st.GetYaxis().SetTitleOffset(1.6)
integral = int(h_neut_med_rel_st.Integral())
h_neut_med_rel_st.SetTitle("Relative #DeltaR = 0.3 Neutral Isolation, 50 < p_{T} < 200 GeV ("+str(integral)+" muons);Uncorrected Neutral #DeltaR = 0.3 Isolation;Fraction")
h_neut_med_rel_st.Scale(1./integral)
h_neut_med_rel_st.GetYaxis().SetTitleOffset(1.6)
integral = int(h_neut_hard_rel_st.Integral())
h_neut_hard_rel_st.SetTitle("Relative #DeltaR = 0.3 Neutral Isolation, p_{T} > 200 GeV ("+str(integral)+" muons);Uncorrected Neutral #DeltaR = 0.3 Isolation;Fraction")
h_neut_hard_rel_st.Scale(1./integral)
h_neut_hard_rel_st.GetYaxis().SetTitleOffset(1.6)


#################

##############
# Make Plots #
##############

#################

canvas = ROOT.TCanvas()
canvas.SetCanvasSize(700,700)
pads = [canvas]
pads[0].SetLeftMargin(0.12)
pads[0].SetTopMargin(0.12)
pads[0].SetRightMargin(0.12)
pads[0].cd()

tl = ROOT.TLegend(0.20,0.75,0.40,0.85)
tl.AddEntry(h_median_dB,"Median #Delta#beta")
tl.AddEntry(h_median_EA,"Median Effective Area")
h_median_dB.Draw()
h_median_EA.Draw("same")
tl.Draw()
canvas.SaveAs("PDFs/median_corrs.pdf")

canvas.SetLogy(True)

h_all_EAcorrs.Draw("hist")
canvas.SaveAs("PDFs/all_EAcorrs.pdf")
h_all_dBcorrs.Draw("hist")
canvas.SaveAs("PDFs/all_dBcorrs.pdf")

h_diffCorr_low_bar.Draw("hist")
canvas.SaveAs("PDFs/diffCorr_low_bar.pdf")
h_diffCorr_low_cap.Draw("hist")
canvas.SaveAs("PDFs/diffCorr_low_cap.pdf")
h_diffCorr_med_bar.Draw("hist")
canvas.SaveAs("PDFs/diffCorr_med_bar.pdf")
h_diffCorr_med_cap.Draw("hist")
canvas.SaveAs("PDFs/diffCorr_med_cap.pdf")
h_diffCorr_high_bar.Draw("hist")
canvas.SaveAs("PDFs/diffCorr_high_bar.pdf")
h_diffCorr_high_cap.Draw("hist")
canvas.SaveAs("PDFs/diffCorr_high_cap.pdf")

h_neut_low_bar.Draw("hist")
canvas.SaveAs("PDFs/neut_low_bar.pdf")
h_neut_low_cap.Draw("hist")
canvas.SaveAs("PDFs/neut_low_cap.pdf")
h_neut_med_bar.Draw("hist")
canvas.SaveAs("PDFs/neut_med_bar.pdf")
h_neut_med_cap.Draw("hist")
canvas.SaveAs("PDFs/neut_med_cap.pdf")
h_neut_high_bar.Draw("hist")
canvas.SaveAs("PDFs/neut_high_bar.pdf")
h_neut_high_cap.Draw("hist")
canvas.SaveAs("PDFs/neut_high_cap.pdf")

h_neut_soft.Draw("hist")
canvas.SaveAs("PDFs/neut_soft.pdf")
h_neut_med.Draw("hist")
canvas.SaveAs("PDFs/neut_med.pdf")
h_neut_hard.Draw("hist")
canvas.SaveAs("PDFs/neut_hard.pdf")

#Relative 

canvas.SetLogy(False)
tl.Clear()
tl.AddEntry(h_median_dB_rel,"Median #Delta#beta")
tl.AddEntry(h_median_EA_rel,"Median Effective Area")
h_median_dB_rel.Draw()
h_median_EA_rel.Draw("same")
tl.Draw()
canvas.SaveAs("PDFs/median_corrs_rel.pdf")
canvas.SetLogy(True)

h_all_EAcorrs_rel.Draw("hist")
canvas.SaveAs("PDFs/all_EAcorrs_rel.pdf")
h_all_dBcorrs_rel.Draw("hist")
canvas.SaveAs("PDFs/all_dBcorrs_rel.pdf")

h_diffCorr_low_bar_rel.Draw("hist")
canvas.SaveAs("PDFs/diffCorr_low_bar_rel.pdf")
h_diffCorr_low_cap_rel.Draw("hist")
canvas.SaveAs("PDFs/diffCorr_low_cap_rel.pdf")
h_diffCorr_med_bar_rel.Draw("hist")
canvas.SaveAs("PDFs/diffCorr_med_bar_rel.pdf")
h_diffCorr_med_cap_rel.Draw("hist")
canvas.SaveAs("PDFs/diffCorr_med_cap_rel.pdf")
h_diffCorr_high_bar_rel.Draw("hist")
canvas.SaveAs("PDFs/diffCorr_high_bar_rel.pdf")
h_diffCorr_high_cap_rel.Draw("hist")
canvas.SaveAs("PDFs/diffCorr_high_cap_rel.pdf")

h_neut_low_bar_rel.Draw("hist")
canvas.SaveAs("PDFs/neut_low_bar_rel.pdf")
h_neut_low_cap_rel.Draw("hist")
canvas.SaveAs("PDFs/neut_low_cap_rel.pdf")
h_neut_med_bar_rel.Draw("hist")
canvas.SaveAs("PDFs/neut_med_bar_rel.pdf")
h_neut_med_cap_rel.Draw("hist")
canvas.SaveAs("PDFs/neut_med_cap_rel.pdf")
h_neut_high_bar_rel.Draw("hist")
canvas.SaveAs("PDFs/neut_high_bar_rel.pdf")
h_neut_high_cap_rel.Draw("hist")
canvas.SaveAs("PDFs/neut_high_cap_rel.pdf")

h_neut_soft_rel.Draw("hist")
canvas.SaveAs("PDFs/neut_soft_rel.pdf")
h_neut_med_rel.Draw("hist")
canvas.SaveAs("PDFs/neut_med_rel.pdf")
h_neut_hard_rel.Draw("hist")
canvas.SaveAs("PDFs/neut_hard_rel.pdf")


############
# Standard #
############

canvas.SetLogy(False)
tl.Clear()
tl.AddEntry(h_median_dB_st,"Median #Delta#beta")
tl.AddEntry(h_median_EA_st,"Median Effective Area")
h_median_dB_st.Draw()
h_median_EA_st.Draw("same")
tl.Draw()
canvas.SaveAs("PDFs/median_corrs_st.pdf")
canvas.SetLogy(True)

h_all_EAcorrs_st.Draw()
canvas.SaveAs("PDFs/all_EAcorrs_st.pdf")
h_all_dBcorrs_st.Draw()
canvas.SaveAs("PDFs/all_dBcorrs_st.pdf")

h_diffCorr_low_bar_st.Draw("hist")
canvas.SaveAs("PDFs/diffCorr_low_bar_st.pdf")
h_diffCorr_low_cap.Draw("hist")
canvas.SaveAs("PDFs/diffCorr_low_cap_st.pdf")
h_diffCorr_med_bar_st.Draw("hist")
canvas.SaveAs("PDFs/diffCorr_med_bar_st.pdf")
h_diffCorr_med_cap.Draw("hist")
canvas.SaveAs("PDFs/diffCorr_med_cap_st.pdf")
h_diffCorr_high_bar_st.Draw("hist")
canvas.SaveAs("PDFs/diffCorr_high_bar_st.pdf")
h_diffCorr_high_cap.Draw("hist")
canvas.SaveAs("PDFs/diffCorr_high_cap_st.pdf")

h_neut_low_bar_st.Draw("hist")
canvas.SaveAs("PDFs/neut_low_bar_st.pdf")
h_neut_low_cap.Draw("hist")
canvas.SaveAs("PDFs/neut_low_cap_st.pdf")
h_neut_med_bar_st.Draw("hist")
canvas.SaveAs("PDFs/neut_med_bar_st.pdf")
h_neut_med_cap.Draw("hist")
canvas.SaveAs("PDFs/neut_med_cap_st.pdf")
h_neut_high_bar_st.Draw("hist")
canvas.SaveAs("PDFs/neut_high_bar_st.pdf")
h_neut_high_cap.Draw("hist")
canvas.SaveAs("PDFs/neut_high_cap_st.pdf")

h_neut_soft_st.Draw("hist")
canvas.SaveAs("PDFs/neut_soft_st.pdf")
h_neut_med_st.Draw("hist")
canvas.SaveAs("PDFs/neut_med_st.pdf")
h_neut_hard_st.Draw("hist")
canvas.SaveAs("PDFs/neut_hard_st.pdf")


#Relative 

canvas.SetLogy(False)
tl.Clear()
tl.AddEntry(h_median_dB_rel_st,"Median #Delta#beta")
tl.AddEntry(h_median_EA_rel_st,"Median Effective Area")
h_median_dB_rel_st.Draw()
h_median_EA_rel_st.Draw("same")
tl.Draw()
canvas.SaveAs("PDFs/median_corrs_rel_st.pdf")
canvas.SetLogy(True)

h_all_EAcorrs_rel_st.Draw("hist")
canvas.SaveAs("PDFs/all_EAcorrs_rel_st.pdf")
h_all_dBcorrs_rel_st.Draw("hist")
canvas.SaveAs("PDFs/all_dBcorrs_rel_st.pdf")

h_diffCorr_low_bar_rel_st.Draw("hist")
canvas.SaveAs("PDFs/diffCorr_low_bar_rel_st.pdf")
h_diffCorr_low_cap_rel_st.Draw("hist")
canvas.SaveAs("PDFs/diffCorr_low_cap_rel_st.pdf")
h_diffCorr_med_bar_rel_st.Draw("hist")
canvas.SaveAs("PDFs/diffCorr_med_bar_rel_st.pdf")
h_diffCorr_med_cap_rel_st.Draw("hist")
canvas.SaveAs("PDFs/diffCorr_med_cap_rel_st.pdf")
h_diffCorr_high_bar_rel_st.Draw("hist")
canvas.SaveAs("PDFs/diffCorr_high_bar_rel_st.pdf")
h_diffCorr_high_cap_rel_st.Draw("hist")
canvas.SaveAs("PDFs/diffCorr_high_cap_rel_st.pdf")

h_neut_low_bar_rel_st.Draw("hist")
canvas.SaveAs("PDFs/neut_low_bar_rel_st.pdf")
h_neut_low_cap_rel_st.Draw("hist")
canvas.SaveAs("PDFs/neut_low_cap_rel_st.pdf")
h_neut_med_bar_rel_st.Draw("hist")
canvas.SaveAs("PDFs/neut_med_bar_rel_st.pdf")
h_neut_med_cap_rel_st.Draw("hist")
canvas.SaveAs("PDFs/neut_med_cap_rel_st.pdf")
h_neut_high_bar_rel_st.Draw("hist")
canvas.SaveAs("PDFs/neut_high_bar_rel_st.pdf")
h_neut_high_cap_rel_st.Draw("hist")
canvas.SaveAs("PDFs/neut_high_cap_rel_st.pdf")

h_neut_soft_rel_st.Draw("hist")
canvas.SaveAs("PDFs/neut_soft_rel_st.pdf")
h_neut_med_rel_st.Draw("hist")
canvas.SaveAs("PDFs/neut_med_rel_st.pdf")
h_neut_hard_rel_st.Draw("hist")
canvas.SaveAs("PDFs/neut_hard_rel_st.pdf")

# rhos and TProfiles

canvas.SetLogy(False)

p_pt_EA.SetTitleOffset(1.6,"y")
p_pt_EA.SetTitle("#DeltaR=0.3 EA Corrections by p_{T} of Candidate;Muon p_{T} (GeV);Average Absolute EA Correction (GeV)")
p_pt_EA.Draw()
canvas.SaveAs("PDFs/p_pt_EA.pdf")
p_pt_dB.SetTitle("#DeltaR=0.3 #Delta#beta Corrections by p_{T} of Candidate;Muon p_{T} (GeV);Average Absolute #Delta#beta Correction (GeV)")
p_pt_dB.SetTitleOffset(1.6,"y")
p_pt_dB.Draw()
canvas.SaveAs("PDFs/p_pt_dB.pdf")
p_npv_EA.SetTitle("#DeltaR=0.3 Corrections by N_{PV};Number of Pileup Vertices;Average Absolute Correction (GeV)")
p_npv_EA.SetTitleOffset(1.6,"y")
p_npv_EA.SetLineColor(ROOT.kRed)
tl.Clear()
tl.AddEntry(p_npv_EA,"Effective Area")
tl.AddEntry(p_npv_dB,"#Delta#beta")
p_npv_EA.SetMaximum(3)
p_npv_EA.Draw()
p_npv_dB.Draw("same")
tl.Draw()
canvas.SaveAs("PDFs/p_npv.pdf")
#p_npv_dB.SetTitle("#DeltaR=0.3 #Delta#beta Corrections by N_{PV};Number of Pileup Vertices;Average #Delta#beta Correction (GeV)")
#p_npv_dB.SetTitleOffset(1.6,"y")
#canvas.SaveAs("PDFs/p_npv_dB.pdf")
integral = int(h_all_rhos_ctr.Integral())
h_all_rhos_ctr.Scale(1./integral)
h_all_rhos_ctr.SetTitle("Central #rho Distribution;#rho (GeV);Fraction")
h_all_rhos_ctr.SetTitleOffset(1.6,"y")
h_all_rhos_ctr.Draw("hist")
canvas.SaveAs("PDFs/rhos_ctr.pdf")
integral = int(h_all_rhos_all.Integral())
h_all_rhos_all.Scale(1./integral)
h_all_rhos_all.SetTitle("Full-Detector #rho Distribution;#rho (GeV);Fraction")
h_all_rhos_all.SetTitleOffset(1.6,"y")
h_all_rhos_all.Draw("hist")
canvas.SaveAs("PDFs/rhos_all.pdf")
p_npv_rhos_all.SetTitle("#rho as Function of N_{PV};Number of Pileup Vertices;Average #rho (GeV)")
p_npv_rhos_all.SetTitleOffset(1.6,"y")
p_npv_rhos_all.SetLineColor(ROOT.kRed)
p_npv_rhos_all.SetMinimum(0)
tl.Clear()
tl.AddEntry(p_npv_rhos_all,"Full-Detector #rho")
tl.AddEntry(p_npv_rhos_ctr,"Central #rho")
p_npv_rhos_all.Draw()
p_npv_rhos_ctr.Draw("same")
tl.Draw()
canvas.SaveAs("PDFs/p_npv_rhos.pdf")
#p_npv_rhos_ctr.SetTitle("Central #rho as Function of N_{PV};Number of Pileup Vertices;Average #rho (GeV)")
#p_npv_rhos_ctr.SetTitleOffset(1.6,"y")
#canvas.SaveAs("PDFs/p_npv_rhos_ctr.pdf")

h_npv_over_EA.SetTitle("Fraction of Overcorrections by N_{PV} (Neut Iso < Correction);Number of Pileup Vertices;Overcorrected Fraction")
h_npv_over_EA.SetTitleOffset(1.6,"y")
h_npv_over_EA.SetLineColor(ROOT.kRed)
h_npv_over_EA.SetMaximum(0.8)
h_npv_over_EA.SetMinimum(0.4)
tl.Clear()
tl.AddEntry(h_npv_over_EA,"Effective Area")
tl.AddEntry(h_npv_over_dB,"#Delta#beta")
h_npv_over_EA.Draw()
h_npv_over_dB.Draw("same")
tl.Draw()
canvas.SaveAs("PDFs/overcorrection.pdf")
