import ROOT
import numpy as n
import ppmUtils as utils

ROOT.gROOT.SetBatch(True)
ROOT.gStyle.SetOptStat(False);

def SavePlot (tcanvas, name="plot", extensions=["png","pdf"]):
    utils.DrawCmsText(canvas,text="CMS Preliminary",textFont=62,textSize=0.035)
    for extension in extensions:
        tcanvas.SaveAs(extension+"s/"+name+"."+extension)

def GetHist (tfile, name, overflow = True, title=None, color=None):
    hist = tfile.Get(name)
    #hist.SetMarkerStyle(20)
    #hist.SetMarkerSize(0.9)
    hist.SetLineWidth(3)
    if overflow:
        utils.PutOverflowInLastBin(hist)
        err0 = hist.GetBinError(0)
        err1 = hist.GetBinError(1)
        hist.SetBinContent(0,hist.GetBinContent(0)+hist.GetBinContent(1))
        hist.SetBinError(0,ROOT.TMath.Sqrt(err0**2 + err1**2))
    if title != None:
        hist.SetTitle(title)
    if color != None:
        hist.SetLineColor(color)
    hist.SetTitleOffset(1.6, "y")
    return hist

def Normalize (hist):
    integral = hist.Integral()
    hist.Scale(1./integral)
    return integral

tf = ROOT.TFile("../src/output/hists.root")

# TProfiles
p_pt_EA = GetHist(tf, "p_pt_EA", overflow=False, title="#DeltaR=0.3 EA Corrections by p_{T} of Candidate;Muon p_{T} (GeV);Average Absolute EA Correction (GeV)")
p_pt_dB = GetHist(tf, "p_pt_dB", overflow=False, title="#DeltaR=0.3 #Delta#beta Corrections by p_{T} of Candidate;Muon p_{T} (GeV);Average Absolute #Delta#beta Correction (GeV)")
p_npv_rhos_all = GetHist(tf, "p_npv_rho_all", overflow=False, title="#rho as Function of N_{PV};Number of Pileup Vertices;Average #rho (GeV)",color=ROOT.kRed)
p_npv_rhos_ctr = GetHist(tf, "p_npv_rho_ctr", overflow=False)

h_npv_over_EA = GetHist(tf, "h_npv_over_EA", overflow=False, title="Fraction of Overcorrections by N_{PV} (Neut Iso < Correction);Number of Pileup Vertices;Overcorrected Fraction",color=ROOT.kRed)
h_npv_over_dB = GetHist(tf, "h_npv_over_dB", overflow=False)

########
# Mini #
########

h_all_rhos_ctr = GetHist(tf,"h_all_rhos_ctr", title="Central-Neutral #rho Distribution;#rho (GeV);Fraction")
Normalize(h_all_rhos_ctr)

h_all_EAs = GetHist(tf, "h_all_EAs")
integral = Normalize(h_all_EAs)
h_all_EAs.SetTitle("All Mini Effective Areas ("+str(integral)+" muons);Effective Area;Fraction")

h_median_EA = GetHist(tf, "h_median_EA", overflow=False)
h_median_dB = GetHist(tf, "h_median_dB", overflow=False, title="Median Corrections as Function of N_{PV};N_{PV};Median Absolute MiniIso Correction (GeV)", color=ROOT.kRed)
# Fixed this after initial presentation (median plots aren't correctly rescaled for extra stats)
h_median_EA.Scale(1./269.)
h_median_dB.Scale(1./269.)

h_all_EAcorrs = GetHist(tf, "h_all_EAcorrs")
h_all_dBcorrs = GetHist(tf, "h_all_dBcorrs")
integral = int(Normalize(h_all_EAcorrs))
h_all_EAcorrs.SetTitle("All MiniIso Effective Area Corrections ("+str(integral)+" muons);Absolute Effective Area Correction (GeV);Fraction")
integral = int(Normalize(h_all_dBcorrs))
h_all_dBcorrs.SetTitle("All MiniIso #Delta#beta Corrections ("+str(integral)+" muons);Absolute #Delta#beta Correction (GeV);Fraction")

h_median_EA_rel = GetHist(tf, "h_median_EA_rel", overflow=False)
h_median_dB_rel = GetHist(tf, "h_median_dB_rel", overflow=False, title="Median Corrections as Function of N_{PV};N_{PV};Median Relative MiniIso Correction", color=ROOT.kRed)
h_median_EA_rel.Scale(1./269.)
h_median_dB_rel.Scale(1./269.)

h_all_EAcorrs_rel = GetHist(tf, "h_all_EAcorrs_rel")
h_all_dBcorrs_rel = GetHist(tf, "h_all_dBcorrs_rel")
integral = int(Normalize(h_all_EAcorrs_rel))
h_all_EAcorrs_rel.SetTitle("All Relative MiniIso Effective Area Corrections ("+str(integral)+" muons);Effective Area Correction;Fraction")
h_all_EAcorrs_rel.Scale(1./integral)
integral = int(Normalize(h_all_dBcorrs_rel))
h_all_dBcorrs_rel.SetTitle("All Relative MiniIso #Delta#beta Corrections ("+str(integral)+" muons);#Delta#beta Correction;Fraction")

h_diff_0p8_EA = GetHist(tf, "h_diff_0p8_EA", title="Abs Neut MiniIso - Effective Area Correction;Difference (GeV);Fraction")
h_diff_1p3_EA = GetHist(tf, "h_diff_1p3_EA", color=ROOT.kRed)
h_diff_2p0_EA = GetHist(tf, "h_diff_2p0_EA", color=ROOT.kGreen)
h_diff_2p2_EA = GetHist(tf, "h_diff_2p2_EA", color=ROOT.kCyan)
h_diff_2p5_EA = GetHist(tf, "h_diff_2p5_EA", color=ROOT.kMagenta)
Normalize(h_diff_0p8_EA)
h_diff_0p8_EA.SetMaximum(0.5)
Normalize(h_diff_1p3_EA)
Normalize(h_diff_2p0_EA)
Normalize(h_diff_2p2_EA)
Normalize(h_diff_2p5_EA)

h_diff_0p8_dB = GetHist(tf, "h_diff_0p8_dB", title="Abs Neut MiniIso - #Delta#beta Correction;Difference (GeV);Fraction")
h_diff_1p3_dB = GetHist(tf, "h_diff_1p3_dB", color=ROOT.kRed)
h_diff_2p0_dB = GetHist(tf, "h_diff_2p0_dB", color=ROOT.kGreen)
h_diff_2p2_dB = GetHist(tf, "h_diff_2p2_dB", color=ROOT.kCyan)
h_diff_2p5_dB = GetHist(tf, "h_diff_2p5_dB", color=ROOT.kMagenta)
Normalize(h_diff_0p8_dB)
h_diff_0p8_dB.SetMaximum(0.5)
Normalize(h_diff_1p3_dB)
Normalize(h_diff_2p0_dB)
Normalize(h_diff_2p2_dB)
Normalize(h_diff_2p5_dB)

# Mini Eta-sliced TProfiles
p_npv_incl_EA = GetHist(tf, "p_npv_incl_EA", title="Mean Abs MiniIso and Corrections by N_{PV}, Inclusive;N_{PV};Mean (GeV)",overflow=False)
p_npv_incl_dB = GetHist(tf, "p_npv_incl_dB", color=ROOT.kRed,overflow=False)
p_npv_incl_neut = GetHist(tf, "p_npv_incl_neut", color=ROOT.kGreen,overflow=False)

p_npv_0p8_EA = GetHist(tf, "p_npv_0p8_EA", title="Mean Abs MiniIso and Corrections by N_{PV}, |#eta| < 0.8 ;N_{PV};Mean (GeV)",overflow=False)
p_npv_0p8_dB = GetHist(tf, "p_npv_0p8_dB", color=ROOT.kRed,overflow=False)
p_npv_0p8_neut = GetHist(tf, "p_npv_0p8_neut", color=ROOT.kGreen,overflow=False)

p_npv_1p3_EA = GetHist(tf, "p_npv_1p3_EA", title="Mean Abs MiniIso and Corrections by N_{PV}, 0.8 < |#eta| < 1.3 ;N_{PV};Mean (GeV)",overflow=False)
p_npv_1p3_dB = GetHist(tf, "p_npv_1p3_dB", color=ROOT.kRed,overflow=False)
p_npv_1p3_neut = GetHist(tf, "p_npv_1p3_neut", color=ROOT.kGreen,overflow=False)

p_npv_2p0_EA = GetHist(tf, "p_npv_2p0_EA", title="Mean Abs MiniIso and Corrections by N_{PV}, 1.3 < |#eta| < 2.0 ;N_{PV};Mean (GeV)",overflow=False)
p_npv_2p0_dB = GetHist(tf, "p_npv_2p0_dB",color=ROOT.kRed,overflow=False)
p_npv_2p0_neut = GetHist(tf, "p_npv_2p0_neut",color=ROOT.kGreen,overflow=False)

p_npv_2p2_EA = GetHist(tf, "p_npv_2p2_EA", title="Mean Abs MiniIso and Corrections by N_{PV}, 2.0 < |#eta| < 2.2 ;N_{PV};Mean (GeV)",overflow=False)
p_npv_2p2_dB = GetHist(tf, "p_npv_2p2_dB",color=ROOT.kRed,overflow=False)
p_npv_2p2_neut = GetHist(tf, "p_npv_2p2_neut",color=ROOT.kGreen,overflow=False)

p_npv_2p5_EA = GetHist(tf, "p_npv_2p5_EA", title="Mean Abs MiniIso and Corrections by N_{PV}, 2.2 < |#eta| < 2.5 ;N_{PV};Mean (GeV)",overflow=False)
p_npv_2p5_dB = GetHist(tf, "p_npv_2p5_dB",color=ROOT.kRed,overflow=False)
p_npv_2p5_neut = GetHist(tf, "p_npv_2p5_neut",color=ROOT.kGreen,overflow=False)

# Standard Eta-sliced TProfiles
p_npv_incl_EA_st = GetHist(tf, "p_npv_incl_EA_st", title="Mean Abs #DeltaR=0.3 Iso and Corrections by N_{PV}, Inclusive;N_{PV};Mean (GeV)",overflow=False)
p_npv_incl_dB_st = GetHist(tf, "p_npv_incl_dB_st", color=ROOT.kRed,overflow=False)
p_npv_incl_neut_st = GetHist(tf, "p_npv_incl_neut_st", color=ROOT.kGreen,overflow=False)

p_npv_0p8_EA_st = GetHist(tf, "p_npv_0p8_EA_st", title="Mean Abs #DeltaR=0.3 Iso and Corrections by N_{PV}, |#eta| < 0.8 ;N_{PV};Mean (GeV)",overflow=False)
p_npv_0p8_dB_st = GetHist(tf, "p_npv_0p8_dB_st",color=ROOT.kRed,overflow=False)
p_npv_0p8_neut_st = GetHist(tf, "p_npv_0p8_neut_st",color=ROOT.kGreen,overflow=False)

p_npv_1p3_EA_st = GetHist(tf, "p_npv_1p3_EA_st", title="Mean Abs #DeltaR=0.3 Iso and Corrections by N_{PV}, 0.8 < |#eta| < 1.3 ;N_{PV};Mean (GeV)",overflow=False)
p_npv_1p3_dB_st = GetHist(tf, "p_npv_1p3_dB_st",color=ROOT.kRed,overflow=False)
p_npv_1p3_neut_st = GetHist(tf, "p_npv_1p3_neut_st",color=ROOT.kGreen,overflow=False)

p_npv_2p0_EA_st = GetHist(tf, "p_npv_2p0_EA_st", title="Mean Abs #DeltaR=0.3 Iso and Corrections by N_{PV}, 1.3 < |#eta| < 2.0 ;N_{PV};Mean (GeV)",overflow=False)
p_npv_2p0_dB_st = GetHist(tf, "p_npv_2p0_dB_st",color=ROOT.kRed,overflow=False)
p_npv_2p0_neut_st = GetHist(tf, "p_npv_2p0_neut_st",color=ROOT.kGreen,overflow=False)

p_npv_2p2_EA_st = GetHist(tf, "p_npv_2p2_EA_st", title="Mean Abs #DeltaR=0.3 Iso and Corrections by N_{PV}, 2.0 < |#eta| < 2.2 ;N_{PV};Mean (GeV)",overflow=False)
p_npv_2p2_dB_st = GetHist(tf, "p_npv_2p2_dB_st",color=ROOT.kRed,overflow=False)
p_npv_2p2_neut_st = GetHist(tf, "p_npv_2p2_neut_st",color=ROOT.kGreen,overflow=False)

p_npv_2p5_EA_st = GetHist(tf, "p_npv_2p5_EA_st", title="Mean Abs #DeltaR=0.3 Iso and Corrections by N_{PV}, 2.2 < |#eta| < 2.5 ;N_{PV};Mean (GeV)",overflow=False)
p_npv_2p5_dB_st = GetHist(tf, "p_npv_2p5_dB_st",color=ROOT.kRed,overflow=False)
p_npv_2p5_neut_st = GetHist(tf, "p_npv_2p5_neut_st",color=ROOT.kGreen,overflow=False)

p_npv_incl_NImEA = GetHist(tf, "p_npv_incl_NImEA", title="Mean Neutral MiniIso - EA Correction by N_{PV}, Inclusive;N_{PV};Mean Corrected MiniIso (GeV)",overflow=False)
p_npv_incl_NImEA_st = GetHist(tf, "p_npv_incl_NImEA_st", title="Mean Neutral #DeltaR = 0.3 Iso - EA Correction by N_{PV}, Inclusive;N_{PV};Mean Corrected Iso (GeV)",overflow=False)
p_npv_incl_NImEA.SetMinimum(0)
p_npv_incl_NImEA_st.SetMinimum(0)
p_npv_incl_NImEA.SetMaximum(0.8)
p_npv_incl_NImEA_st.SetMaximum(0.8)

prof_max = 1.5
prof_min = 0.0
p_npv_incl_EA.SetMinimum(prof_min)
p_npv_incl_EA.SetMaximum(prof_max)
p_npv_incl_dB.SetMinimum(prof_min)
p_npv_incl_dB.SetMaximum(prof_max)
p_npv_incl_neut.SetMinimum(prof_min)
p_npv_incl_neut.SetMaximum(prof_max)
p_npv_0p8_EA.SetMinimum(prof_min)
p_npv_0p8_EA.SetMaximum(prof_max)
p_npv_0p8_dB.SetMinimum(prof_min)
p_npv_0p8_dB.SetMaximum(prof_max)
p_npv_0p8_neut.SetMinimum(prof_min)
p_npv_0p8_neut.SetMaximum(prof_max)
p_npv_1p3_EA.SetMinimum(prof_min)
p_npv_1p3_EA.SetMaximum(prof_max)
p_npv_1p3_dB.SetMinimum(prof_min)
p_npv_1p3_dB.SetMaximum(prof_max)
p_npv_1p3_neut.SetMinimum(prof_min)
p_npv_1p3_neut.SetMaximum(prof_max)
p_npv_2p0_EA.SetMinimum(prof_min)
p_npv_2p0_EA.SetMaximum(prof_max)
p_npv_2p0_dB.SetMinimum(prof_min)
p_npv_2p0_dB.SetMaximum(prof_max)
p_npv_2p0_neut.SetMinimum(prof_min)
p_npv_2p0_neut.SetMaximum(prof_max)
p_npv_2p2_EA.SetMinimum(prof_min)
p_npv_2p2_EA.SetMaximum(prof_max)
p_npv_2p2_dB.SetMinimum(prof_min)
p_npv_2p2_dB.SetMaximum(prof_max)
p_npv_2p2_neut.SetMinimum(prof_min)
p_npv_2p2_neut.SetMaximum(prof_max)
p_npv_2p5_EA.SetMinimum(prof_min)
p_npv_2p5_EA.SetMaximum(prof_max)
p_npv_2p5_dB.SetMinimum(prof_min)
p_npv_2p5_dB.SetMaximum(prof_max)
p_npv_2p5_neut.SetMinimum(prof_min)
p_npv_2p5_neut.SetMaximum(prof_max)

prof_max_st = 3.0
prof_min_st = 0.0
p_npv_incl_EA_st.SetMinimum(prof_min_st)
p_npv_incl_EA_st.SetMaximum(prof_max_st)
p_npv_incl_dB_st.SetMinimum(prof_min_st)
p_npv_incl_dB_st.SetMaximum(prof_max_st)
p_npv_incl_neut_st.SetMinimum(prof_min_st)
p_npv_incl_neut_st.SetMaximum(prof_max_st)
p_npv_0p8_EA_st.SetMinimum(prof_min_st)
p_npv_0p8_EA_st.SetMaximum(prof_max_st)
p_npv_0p8_dB_st.SetMinimum(prof_min_st)
p_npv_0p8_dB_st.SetMaximum(prof_max_st)
p_npv_0p8_neut_st.SetMinimum(prof_min_st)
p_npv_0p8_neut_st.SetMaximum(prof_max_st)
p_npv_1p3_EA_st.SetMinimum(prof_min_st)
p_npv_1p3_EA_st.SetMaximum(prof_max_st)
p_npv_1p3_dB_st.SetMinimum(prof_min_st)
p_npv_1p3_dB_st.SetMaximum(prof_max_st)
p_npv_1p3_neut_st.SetMinimum(prof_min_st)
p_npv_1p3_neut_st.SetMaximum(prof_max_st)
p_npv_2p0_EA_st.SetMinimum(prof_min_st)
p_npv_2p0_EA_st.SetMaximum(prof_max_st)
p_npv_2p0_dB_st.SetMinimum(prof_min_st)
p_npv_2p0_dB_st.SetMaximum(prof_max_st)
p_npv_2p0_neut_st.SetMinimum(prof_min_st)
p_npv_2p0_neut_st.SetMaximum(prof_max_st)
p_npv_2p2_EA_st.SetMinimum(prof_min_st)
p_npv_2p2_EA_st.SetMaximum(prof_max_st)
p_npv_2p2_dB_st.SetMinimum(prof_min_st)
p_npv_2p2_dB_st.SetMaximum(prof_max_st)
p_npv_2p2_neut_st.SetMinimum(prof_min_st)
p_npv_2p2_neut_st.SetMaximum(prof_max_st)
p_npv_2p5_EA_st.SetMinimum(prof_min_st)
p_npv_2p5_EA_st.SetMaximum(prof_max_st)
p_npv_2p5_dB_st.SetMinimum(prof_min_st)
p_npv_2p5_dB_st.SetMaximum(prof_max_st)
p_npv_2p5_neut_st.SetMinimum(prof_min_st)
p_npv_2p5_neut_st.SetMaximum(prof_max_st)


############
# Standard #
############

h_all_rhos_all = GetHist(tf, "h_all_rhos_all", title="Full-Detector Inclusive #rho Distribution;#rho (GeV);Fraction")
Normalize(h_all_rhos_all)

h_all_EAs_st = GetHist(tf, "h_all_EAs_st")

h_median_EA_st = GetHist(tf, "h_median_EA_st", overflow=False)
h_median_dB_st = GetHist(tf, "h_median_dB_st", overflow=False, title="Median Corrections as Function of N_{PV};N_{PV};Median Absolute #DeltaR = 0.3 Iso Correction (GeV)", color=ROOT.kRed)
h_median_EA_st.Scale(1./269.)
h_median_dB_st.Scale(1./269.)

h_all_EAcorrs_st = GetHist(tf, "h_all_EAcorrs_st")
h_all_dBcorrs_st = GetHist(tf, "h_all_dBcorrs_st", )
integral = int(Normalize(h_all_dBcorrs_st))
h_all_dBcorrs_st.SetTitle("All #DeltaR = 0.3 Iso #Delta#beta Corrections ("+str(integral)+" muons);#Delta#beta Correction (GeV);Fraction")
integral = int(Normalize(h_all_EAcorrs_st))
h_all_EAcorrs_st.SetTitle("All #DeltaR = 0.3 Iso Effective Area Corrections ("+str(integral)+" muons);Effective Area Correction (GeV);Fraction")

h_median_EA_rel_st = GetHist(tf, "h_median_EA_rel_st", overflow=False)
h_median_dB_rel_st = GetHist(tf, "h_median_dB_rel_st", title="Median Corrections as Function of N_{PV};N_{PV};Median Relative #DeltaR = 0.3 Iso Correction",color=ROOT.kRed, overflow=False)
h_median_EA_rel_st.Scale(1./269.)
h_median_dB_rel_st.Scale(1./269.)

h_all_EAcorrs_rel_st = GetHist(tf, "h_all_EAcorrs_rel_st")
h_all_dBcorrs_rel_st = GetHist(tf, "h_all_dBcorrs_rel_st")
integral = int(Normalize(h_all_EAcorrs_rel_st))
h_all_EAcorrs_rel_st.SetTitle("All #DeltaR = 0.3 Iso Effective Area Corrections ("+str(integral)+" muons);Effective Area Correction;Fraction")
integral = int(Normalize(h_all_dBcorrs_rel_st))
h_all_dBcorrs_rel_st.SetTitle("All #DeltaR = 0.3 Iso #Delta#beta Corrections ("+str(integral)+" muons);#Delta#beta Correction;Fraction")

h_diff_0p8_EA_st = GetHist(tf, "h_diff_0p8_EA_st", title="Abs Neut #DeltaR=0.3 Iso - Effective Area Correction;Difference (GeV);Fraction")
h_diff_1p3_EA_st = GetHist(tf, "h_diff_1p3_EA_st", color=ROOT.kRed)
h_diff_2p0_EA_st = GetHist(tf, "h_diff_2p0_EA_st", color=ROOT.kGreen)
h_diff_2p2_EA_st = GetHist(tf, "h_diff_2p2_EA_st", color=ROOT.kCyan)
h_diff_2p5_EA_st = GetHist(tf, "h_diff_2p5_EA_st", color=ROOT.kMagenta)
Normalize(h_diff_0p8_EA_st)
h_diff_0p8_EA_st.SetMaximum(0.3)
Normalize(h_diff_1p3_EA_st)
Normalize(h_diff_2p0_EA_st)
Normalize(h_diff_2p2_EA_st)
Normalize(h_diff_2p5_EA_st)

h_diff_0p8_dB_st = GetHist(tf, "h_diff_0p8_dB_st", title="Abs Neut #DeltaR=0.3 Iso - #Delta#beta Correction;Difference (GeV);Fraction")
h_diff_1p3_dB_st = GetHist(tf, "h_diff_1p3_dB_st", color=ROOT.kRed)
h_diff_2p0_dB_st = GetHist(tf, "h_diff_2p0_dB_st", color=ROOT.kGreen)
h_diff_2p2_dB_st = GetHist(tf, "h_diff_2p2_dB_st", color=ROOT.kCyan)
h_diff_2p5_dB_st = GetHist(tf, "h_diff_2p5_dB_st", color=ROOT.kMagenta)
Normalize(h_diff_0p8_dB_st)
h_diff_0p8_dB_st.SetMaximum(0.3)
Normalize(h_diff_1p3_dB_st)
Normalize(h_diff_2p0_dB_st)
Normalize(h_diff_2p2_dB_st)
Normalize(h_diff_2p5_dB_st)


#################

##############
# Make Plots #
##############

#################

canvas = ROOT.TCanvas()
canvas.SetCanvasSize(700,700)
canvas.SetTicks(1,2)
pads = [canvas]
pads[0].SetLeftMargin(0.12)
pads[0].SetTopMargin(0.12)
pads[0].SetRightMargin(0.12)
pads[0].cd()

tl = ROOT.TLegend(0.20,0.75,0.40,0.85)

tl.AddEntry(h_median_dB,"Median #Delta#beta")
tl.AddEntry(h_median_EA,"Median Effective Area")
h_median_dB.Draw()
h_median_EA.Draw("same")
tl.Draw()
SavePlot(canvas, "median_corrs")

canvas.SetLogy(True)

h_all_EAcorrs.Draw("hist")
SavePlot(canvas, "all_EAcorrs")
h_all_dBcorrs.Draw("hist")
SavePlot(canvas, "all_dBcorrs")

#Relative 

canvas.SetLogy(False)
tl.Clear()
tl.AddEntry(h_median_dB_rel,"Median #Delta#beta")
tl.AddEntry(h_median_EA_rel,"Median Effective Area")
h_median_dB_rel.Draw()
h_median_EA_rel.Draw("same")
tl.Draw()
SavePlot(canvas, "median_corrs_rel")
canvas.SetLogy(True)

h_all_EAcorrs_rel.Draw("hist")
SavePlot(canvas, "all_EAcorrs_rel")
h_all_dBcorrs_rel.Draw("hist")
SavePlot(canvas, "all_dBcorrs_rel")

############
# Standard #
############

canvas.SetLogy(False)
tl.Clear()
tl.AddEntry(h_median_dB_st,"Median #Delta#beta")
tl.AddEntry(h_median_EA_st,"Median Effective Area")
h_median_dB_st.Draw()
h_median_EA_st.Draw("same")
tl.Draw()
SavePlot(canvas, "median_corrs_st")
canvas.SetLogy(True)

h_all_EAcorrs_st.Draw()
SavePlot(canvas, "all_EAcorrs_st")
h_all_dBcorrs_st.Draw()
SavePlot(canvas, "all_dBcorrs_st")

#Relative 

canvas.SetLogy(False)
tl.Clear()
tl.AddEntry(h_median_dB_rel_st,"Median #Delta#beta")
tl.AddEntry(h_median_EA_rel_st,"Median Effective Area")
h_median_dB_rel_st.Draw()
h_median_EA_rel_st.Draw("same")
tl.Draw()
SavePlot(canvas,"median_corrs_rel_st")
canvas.SetLogy(True)

h_all_EAcorrs_rel_st.Draw("hist")
SavePlot(canvas, "all_EAcorrs_rel_st")
h_all_dBcorrs_rel_st.Draw("hist")
SavePlot(canvas, "all_dBcorrs_rel_st")

# rhos and TProfiles

canvas.SetLogy(False)

p_pt_EA.Draw()
SavePlot(canvas,"p_pt_EA")
p_pt_dB.Draw()
SavePlot(canvas, "p_pt_dB")
h_all_rhos_ctr.Draw("hist")
SavePlot(canvas, "rhos_ctr")
h_all_rhos_all.Draw("hist")
SavePlot(canvas, "rhos_all")

p_npv_rhos_all.SetMinimum(0)
tl.Clear()
tl.AddEntry(p_npv_rhos_all,"Full-Detector Incl #rho")
tl.AddEntry(p_npv_rhos_ctr,"Central-Neutral #rho")
p_npv_rhos_all.Draw()
p_npv_rhos_ctr.Draw("same")
tl.Draw()
SavePlot(canvas, "p_npv_rhos")

h_npv_over_EA.SetMaximum(0.8)
h_npv_over_EA.SetMinimum(0.4)
tl.Clear()
tl.AddEntry(h_npv_over_EA,"Effective Area")
tl.AddEntry(h_npv_over_dB,"#Delta#beta")
h_npv_over_EA.Draw()
h_npv_over_dB.Draw("same")
tl.Draw()
SavePlot(canvas, "overcorrection")

tl.Clear()
tl.AddEntry(h_diff_0p8_EA,"|#eta| < 0.8")
tl.AddEntry(h_diff_1p3_EA,"0.8 < |#eta| < 1.3")
tl.AddEntry(h_diff_2p0_EA,"1.3 < |#eta| < 2.0")
tl.AddEntry(h_diff_2p2_EA,"2.0 < |#eta| < 2.2")
tl.AddEntry(h_diff_2p5_EA,"2.2 < |#eta| < 2.5")
h_diff_0p8_EA.Draw()
h_diff_1p3_EA.Draw("same")
h_diff_2p0_EA.Draw("same")
h_diff_2p2_EA.Draw("same")
h_diff_2p5_EA.Draw("same")
tl.Draw()
SavePlot(canvas, "diff_EA")

tl.Clear()
tl.AddEntry(h_diff_0p8_dB,"|#eta| < 0.8")
tl.AddEntry(h_diff_1p3_dB,"0.8 < |#eta| < 1.3")
tl.AddEntry(h_diff_2p0_dB,"1.3 < |#eta| < 2.0")
tl.AddEntry(h_diff_2p2_dB,"2.0 < |#eta| < 2.2")
tl.AddEntry(h_diff_2p5_dB,"2.2 < |#eta| < 2.5")
h_diff_0p8_dB.Draw()
h_diff_1p3_dB.Draw("same")
h_diff_2p0_dB.Draw("same")
h_diff_2p2_dB.Draw("same")
h_diff_2p5_dB.Draw("same")
tl.Draw()
SavePlot(canvas, "diff_dB")

tl.Clear()
tl.AddEntry(h_diff_0p8_EA_st,"|#eta| < 0.8")
tl.AddEntry(h_diff_1p3_EA_st,"0.8 < |#eta| < 1.3")
tl.AddEntry(h_diff_2p0_EA_st,"1.3 < |#eta| < 2.0")
tl.AddEntry(h_diff_2p2_EA_st,"2.0 < |#eta| < 2.2")
tl.AddEntry(h_diff_2p5_EA_st,"2.2 < |#eta| < 2.5")
h_diff_0p8_EA_st.Draw()
h_diff_1p3_EA_st.Draw("same")
h_diff_2p0_EA_st.Draw("same")
h_diff_2p2_EA_st.Draw("same")
h_diff_2p5_EA_st.Draw("same")
tl.Draw()
SavePlot(canvas, "diff_EA_st")

tl.Clear()
tl.AddEntry(h_diff_0p8_dB_st,"|#eta| < 0.8")
tl.AddEntry(h_diff_1p3_dB_st,"0.8 < |#eta| < 1.3")
tl.AddEntry(h_diff_2p0_dB_st,"1.3 < |#eta| < 2.0")
tl.AddEntry(h_diff_2p2_dB_st,"2.0 < |#eta| < 2.2")
tl.AddEntry(h_diff_2p5_dB_st,"2.2 < |#eta| < 2.5")
h_diff_0p8_dB_st.Draw()
h_diff_1p3_dB_st.Draw("same")
h_diff_2p0_dB_st.Draw("same")
h_diff_2p2_dB_st.Draw("same")
h_diff_2p5_dB_st.Draw("same")
tl.Draw()
SavePlot(canvas, "diff_dB_st")

tl.Clear()
h_diff_0p8_EA.SetTitle("Neut MiniIso - Corrections, |#eta| < 0.8;Difference (GeV);Fraction")
h_diff_0p8_EA.SetLineColor(ROOT.kBlue)
h_diff_0p8_dB.SetLineColor(ROOT.kRed)
tl.AddEntry(h_diff_0p8_EA,"Eff Area")
tl.AddEntry(h_diff_0p8_dB,"#Delta#beta")
h_diff_0p8_EA.Draw()
h_diff_0p8_dB.Draw("same")
tl.Draw()
SavePlot(canvas, "diff_0p8")

tl.Clear()
h_diff_1p3_EA.SetTitle("Neut MiniIso - Corrections, 0.8 < |#eta| < 1.3;Difference (GeV);Fraction")
h_diff_1p3_EA.SetLineColor(ROOT.kBlue)
h_diff_1p3_dB.SetLineColor(ROOT.kRed)
tl.AddEntry(h_diff_1p3_EA,"Eff Area")
tl.AddEntry(h_diff_1p3_dB,"#Delta#beta")
h_diff_1p3_EA.Draw()
h_diff_1p3_dB.Draw("same")
tl.Draw()
SavePlot(canvas, "diff_1p3")

tl.Clear()
h_diff_2p0_EA.SetTitle("Neut MiniIso - Corrections, 1.3 < |#eta| < 2.0;Difference (GeV);Fraction")
h_diff_2p0_EA.SetLineColor(ROOT.kBlue)
h_diff_2p0_dB.SetLineColor(ROOT.kRed)
tl.AddEntry(h_diff_2p0_EA,"Eff Area")
tl.AddEntry(h_diff_2p0_dB,"#Delta#beta")
h_diff_2p0_EA.Draw()
h_diff_2p0_dB.Draw("same")
tl.Draw()
SavePlot(canvas, "diff_2p0")

tl.Clear()
h_diff_2p2_EA.SetTitle("Neut MiniIso - Corrections, 2.0 < |#eta| < 2.2;Difference (GeV);Fraction")
h_diff_2p2_EA.SetLineColor(ROOT.kBlue)
h_diff_2p2_dB.SetLineColor(ROOT.kRed)
tl.AddEntry(h_diff_2p2_EA,"Eff Area")
tl.AddEntry(h_diff_2p2_dB,"#Delta#beta")
h_diff_2p2_EA.Draw()
h_diff_2p2_dB.Draw("same")
tl.Draw()
SavePlot(canvas, "diff_2p2")

tl.Clear()
h_diff_2p5_EA.SetTitle("Neut MiniIso - Corrections, 2.2 < |#eta| < 2.5;Difference (GeV);Fraction")
h_diff_2p5_EA.SetLineColor(ROOT.kBlue)
h_diff_2p5_dB.SetLineColor(ROOT.kRed)
tl.AddEntry(h_diff_2p5_EA,"Eff Area")
tl.AddEntry(h_diff_2p5_dB,"#Delta#beta")
h_diff_2p5_EA.Draw()
h_diff_2p5_dB.Draw("same")
tl.Draw()
SavePlot(canvas, "diff_2p5")

tl.Clear()
h_diff_0p8_EA_st.SetTitle("Neut Iso - Corrections, |#eta| < 0.8;Difference (GeV);Fraction")
h_diff_0p8_EA_st.SetLineColor(ROOT.kBlue)
h_diff_0p8_dB_st.SetLineColor(ROOT.kRed)
tl.AddEntry(h_diff_0p8_EA_st,"Eff Area")
tl.AddEntry(h_diff_0p8_dB_st,"#Delta#beta")
h_diff_0p8_EA_st.Draw()
h_diff_0p8_dB_st.Draw("same")
tl.Draw()
SavePlot(canvas, "diff_0p8_st")

tl.Clear()
h_diff_1p3_EA_st.SetTitle("Neut Iso - Corrections, 0.8 < |#eta| < 1.3;Difference (GeV);Fraction")
h_diff_1p3_EA_st.SetLineColor(ROOT.kBlue)
h_diff_1p3_dB_st.SetLineColor(ROOT.kRed)
tl.AddEntry(h_diff_1p3_EA_st,"Eff Area")
tl.AddEntry(h_diff_1p3_dB_st,"#Delta#beta")
h_diff_1p3_EA_st.Draw()
h_diff_1p3_dB_st.Draw("same")
tl.Draw()
SavePlot(canvas, "diff_1p3_st")

tl.Clear()
h_diff_2p0_EA_st.SetTitle("Neut Iso - Corrections, 1.3 < |#eta| < 2.0;Difference (GeV);Fraction")
h_diff_2p0_EA_st.SetLineColor(ROOT.kBlue)
h_diff_2p0_dB_st.SetLineColor(ROOT.kRed)
tl.AddEntry(h_diff_2p0_EA_st,"Eff Area")
tl.AddEntry(h_diff_2p0_dB_st,"#Delta#beta")
h_diff_2p0_EA_st.Draw()
h_diff_2p0_dB_st.Draw("same")
tl.Draw()
SavePlot(canvas, "diff_2p0_st")

tl.Clear()
h_diff_2p2_EA_st.SetTitle("Neut Iso - Corrections, 2.0 < |#eta| < 2.2;Difference (GeV);Fraction")
h_diff_2p2_EA_st.SetLineColor(ROOT.kBlue)
h_diff_2p2_dB_st.SetLineColor(ROOT.kRed)
tl.AddEntry(h_diff_2p2_EA_st,"Eff Area")
tl.AddEntry(h_diff_2p2_dB_st,"#Delta#beta")
h_diff_2p2_EA_st.Draw()
h_diff_2p2_dB_st.Draw("same")
tl.Draw()
SavePlot(canvas, "diff_2p2_st")

tl.Clear()
h_diff_2p5_EA_st.SetTitle("Neut Iso - Corrections, 2.2 < |#eta| < 2.5;Difference (GeV);Fraction")
h_diff_2p5_EA_st.SetLineColor(ROOT.kBlue)
h_diff_2p5_dB_st.SetLineColor(ROOT.kRed)
tl.AddEntry(h_diff_2p5_EA_st,"Eff Area")
tl.AddEntry(h_diff_2p5_dB_st,"#Delta#beta")
h_diff_2p5_EA_st.Draw()
h_diff_2p5_dB_st.Draw("same")
tl.Draw()
SavePlot(canvas, "diff_2p5_st")


tl.Clear()
tl.AddEntry(p_npv_incl_neut,"Neut Iso")
tl.AddEntry(p_npv_incl_EA,"Eff Area")
tl.AddEntry(p_npv_incl_dB,"#Delta#beta")
p_npv_incl_EA.Draw()
p_npv_incl_dB.Draw("same")
p_npv_incl_neut.Draw("same")
tl.Draw()
SavePlot(canvas, "mini_incl")

tl.Clear()
tl.AddEntry(p_npv_0p8_neut,"Neut Iso")
tl.AddEntry(p_npv_0p8_EA,"Eff Area")
tl.AddEntry(p_npv_0p8_dB,"#Delta#beta")
p_npv_0p8_EA.Draw()
p_npv_0p8_dB.Draw("same")
p_npv_0p8_neut.Draw("same")
tl.Draw()
SavePlot(canvas, "mini_0p8")

tl.Clear()
tl.AddEntry(p_npv_1p3_neut,"Neut Iso")
tl.AddEntry(p_npv_1p3_EA,"Eff Area")
tl.AddEntry(p_npv_1p3_dB,"#Delta#beta")
p_npv_1p3_EA.Draw()
p_npv_1p3_dB.Draw("same")
p_npv_1p3_neut.Draw("same")
tl.Draw()
SavePlot(canvas, "mini_1p3")

tl.Clear()
tl.AddEntry(p_npv_2p0_neut,"Neut Iso")
tl.AddEntry(p_npv_2p0_EA,"Eff Area")
tl.AddEntry(p_npv_2p0_dB,"#Delta#beta")
p_npv_2p0_EA.Draw()
p_npv_2p0_dB.Draw("same")
p_npv_2p0_neut.Draw("same")
tl.Draw()
SavePlot(canvas, "mini_2p0")

tl.Clear()
tl.AddEntry(p_npv_2p2_neut,"Neut Iso")
tl.AddEntry(p_npv_2p2_EA,"Eff Area")
tl.AddEntry(p_npv_2p2_dB,"#Delta#beta")
p_npv_2p2_EA.Draw()
p_npv_2p2_dB.Draw("same")
p_npv_2p2_neut.Draw("same")
tl.Draw()
SavePlot(canvas, "mini_2p2")

tl.Clear()
tl.AddEntry(p_npv_2p5_neut,"Neut Iso")
tl.AddEntry(p_npv_2p5_EA,"Eff Area")
tl.AddEntry(p_npv_2p5_dB,"#Delta#beta")
p_npv_2p5_EA.Draw()
p_npv_2p5_dB.Draw("same")
p_npv_2p5_neut.Draw("same")
tl.Draw()
SavePlot(canvas, "mini_2p5")

tl.Clear()
tl.AddEntry(p_npv_incl_neut_st,"Neut Iso")
tl.AddEntry(p_npv_incl_EA_st,"Eff Area")
tl.AddEntry(p_npv_incl_dB_st,"#Delta#beta")
p_npv_incl_EA_st.Draw()
p_npv_incl_dB_st.Draw("same")
p_npv_incl_neut_st.Draw("same")
tl.Draw()
SavePlot(canvas, "fixedcone_incl")

tl.Clear()
tl.AddEntry(p_npv_0p8_neut_st,"Neut Iso")
tl.AddEntry(p_npv_0p8_EA_st,"Eff Area")
tl.AddEntry(p_npv_0p8_dB_st,"#Delta#beta")
p_npv_0p8_EA_st.Draw()
p_npv_0p8_dB_st.Draw("same")
p_npv_0p8_neut_st.Draw("same")
tl.Draw()
SavePlot(canvas, "fixedcone_0p8")

tl.Clear()
tl.AddEntry(p_npv_1p3_neut_st,"Neut Iso")
tl.AddEntry(p_npv_1p3_EA_st,"Eff Area")
tl.AddEntry(p_npv_1p3_dB_st,"#Delta#beta")
p_npv_1p3_EA_st.Draw()
p_npv_1p3_dB_st.Draw("same")
p_npv_1p3_neut_st.Draw("same")
tl.Draw()
SavePlot(canvas, "fixedcone_1p3")

tl.Clear()
tl.AddEntry(p_npv_2p0_neut_st,"Neut Iso")
tl.AddEntry(p_npv_2p0_EA_st,"Eff Area")
tl.AddEntry(p_npv_2p0_dB_st,"#Delta#beta")
p_npv_2p0_EA_st.Draw()
p_npv_2p0_dB_st.Draw("same")
p_npv_2p0_neut_st.Draw("same")
tl.Draw()
SavePlot(canvas, "fixedcone_2p0")

tl.Clear()
tl.AddEntry(p_npv_2p2_neut_st,"Neut Iso")
tl.AddEntry(p_npv_2p2_EA_st,"Eff Area")
tl.AddEntry(p_npv_2p2_dB_st,"#Delta#beta")
p_npv_2p2_EA_st.Draw()
p_npv_2p2_dB_st.Draw("same")
p_npv_2p2_neut_st.Draw("same")
tl.Draw()
SavePlot(canvas, "fixedcone_2p2")

tl.Clear()
tl.AddEntry(p_npv_2p5_neut_st,"Neut Iso")
tl.AddEntry(p_npv_2p5_EA_st,"Eff Area")
tl.AddEntry(p_npv_2p5_dB_st,"#Delta#beta")
p_npv_2p5_EA_st.Draw()
p_npv_2p5_dB_st.Draw("same")
p_npv_2p5_neut_st.Draw("same")
tl.Draw()
SavePlot(canvas, "fixedcone_2p5")

p_npv_incl_NImEA.Draw()
SavePlot(canvas, "NImEA_incl")
p_npv_incl_NImEA_st.Draw()
SavePlot(canvas, "NImEA_incl_st")

print("Remember to fix median plots if you adjusted the number of hadded merged_ntuple_x.root.")
