import ROOT
import numpy as n

ROOT.gROOT.SetBatch(True)
ROOT.gStyle.SetOptStat(False);


tf = ROOT.TFile("../src/merged10x.root")

h_all_rhos = tf.Get("h_all_rhos")

########
# Mini #
########

h_all_EAs = tf.Get("h_all_EAs")

h_median_EA = tf.Get("h_median_EA")
h_median_dB = tf.Get("h_median_dB")

h_all_EAcorrs = tf.Get("h_all_EAcorrs")
h_all_dBcorrs = tf.Get("h_all_dBcorrs")

h_CI_dB_low_bar = tf.Get("h_CI_dB_low_bar")
h_CI_dB_med_bar = tf.Get("h_CI_dB_med_bar")
h_CI_dB_high_bar = tf.Get("h_CI_dB_high_bar")
h_CI_dB_low_cap = tf.Get("h_CI_dB_low_cap")
h_CI_dB_med_cap = tf.Get("h_CI_dB_med_cap")
h_CI_dB_high_cap = tf.Get("h_CI_dB_high_cap")

h_CI_EA_low_bar = tf.Get("h_CI_EA_low_bar")
h_CI_EA_med_bar = tf.Get("h_CI_EA_med_bar")
h_CI_EA_high_bar = tf.Get("h_CI_EA_high_bar")
h_CI_EA_low_cap = tf.Get("h_CI_EA_low_cap")
h_CI_EA_med_cap = tf.Get("h_CI_EA_med_cap")
h_CI_EA_high_cap = tf.Get("h_CI_EA_high_cap")

h_diffCorr_low_bar = tf.Get("h_diffCorr_low_bar")
h_diffCorr_med_bar = tf.Get("h_diffCorr_med_bar")
h_diffCorr_high_bar = tf.Get("h_diffCorr_high_bar")
h_diffCorr_low_cap = tf.Get("h_diffCorr_low_cap")
h_diffCorr_med_cap = tf.Get("h_diffCorr_med_cap")
h_diffCorr_high_cap = tf.Get("h_diffCorr_high_cap")

h_dB_vs_EA_low_bar = tf.Get("h_dB_vs_EA_low_bar")
h_dB_vs_EA_low_cap = tf.Get("h_dB_vs_EA_low_cap")
h_dB_vs_EA_med_bar = tf.Get("h_dB_vs_EA_med_bar")
h_dB_vs_EA_med_cap = tf.Get("h_dB_vs_EA_med_cap")
h_dB_vs_EA_high_bar = tf.Get("h_dB_vs_EA_high_bar")
h_dB_vs_EA_high_cap = tf.Get("h_dB_vs_EA_high_cap")

h_all_EAs_rel = tf.Get("h_all_EAs")

h_median_EA_rel = tf.Get("h_median_EA_rel")
h_median_dB_rel = tf.Get("h_median_dB_rel")

h_all_EAcorrs_rel = tf.Get("h_all_EAcorrs_rel")
h_all_dBcorrs_rel = tf.Get("h_all_dBcorrs_rel")

h_CIrel_dB_low_bar = tf.Get("h_CIrel_dB_low_bar")
h_CIrel_dB_med_bar = tf.Get("h_CIrel_dB_med_bar")
h_CIrel_dB_high_bar = tf.Get("h_CIrel_dB_high_bar")
h_CIrel_dB_low_cap = tf.Get("h_CIrel_dB_low_cap")
h_CIrel_dB_med_cap = tf.Get("h_CIrel_dB_med_cap")
h_CIrel_dB_high_cap = tf.Get("h_CIrel_dB_high_cap")

h_CIrel_EA_low_bar = tf.Get("h_CIrel_EA_low_bar")
h_CIrel_EA_med_bar = tf.Get("h_CIrel_EA_med_bar")
h_CIrel_EA_high_bar = tf.Get("h_CIrel_EA_high_bar")
h_CIrel_EA_low_cap = tf.Get("h_CIrel_EA_low_cap")
h_CIrel_EA_med_cap = tf.Get("h_CIrel_EA_med_cap")
h_CIrel_EA_high_cap = tf.Get("h_CIrel_EA_high_cap")

h_diffCorrRel_low_bar = tf.Get("h_diffCorrRel_low_bar")
h_diffCorrRel_med_bar = tf.Get("h_diffCorrRel_med_bar")
h_diffCorrRel_high_bar = tf.Get("h_diffCorrRel_high_bar")
h_diffCorrRel_low_cap = tf.Get("h_diffCorrRel_low_cap")
h_diffCorrRel_med_cap = tf.Get("h_diffCorrRel_med_cap")
h_diffCorrRel_high_cap = tf.Get("h_diffCorrRel_high_cap")

h_dB_vs_EA_low_bar_rel = tf.Get("h_dB_vs_EA_low_bar_rel")
h_dB_vs_EA_low_cap_rel = tf.Get("h_dB_vs_EA_low_cap_rel")
h_dB_vs_EA_med_bar_rel = tf.Get("h_dB_vs_EA_med_bar_rel")
h_dB_vs_EA_med_cap_rel = tf.Get("h_dB_vs_EA_med_cap_rel")
h_dB_vs_EA_high_bar_rel = tf.Get("h_dB_vs_EA_high_bar_rel")
h_dB_vs_EA_high_cap_rel = tf.Get("h_dB_vs_EA_high_cap_rel")

############
# Standard #
############

h_all_EAs_st = tf.Get("h_all_EAs_st")

h_median_EA_st = tf.Get("h_median_EA_st")
h_median_dB_st = tf.Get("h_median_dB_st")

h_all_EAcorrs_st = tf.Get("h_all_EAcorrs_st")
h_all_dBcorrs_st = tf.Get("h_all_dBcorrs_st")

h_CI_dB_low_bar_st = tf.Get("h_CI_dB_low_bar_st")
h_CI_dB_med_bar_st = tf.Get("h_CI_dB_med_bar_st")
h_CI_dB_high_bar_st = tf.Get("h_CI_dB_high_bar_st")
h_CI_dB_low_cap_st = tf.Get("h_CI_dB_low_cap_st")
h_CI_dB_med_cap_st = tf.Get("h_CI_dB_med_cap_st")
h_CI_dB_high_cap_st = tf.Get("h_CI_dB_high_cap_st")

h_CI_EA_low_bar_st = tf.Get("h_CI_EA_low_bar_st")
h_CI_EA_med_bar_st = tf.Get("h_CI_EA_med_bar_st")
h_CI_EA_high_bar_st = tf.Get("h_CI_EA_high_bar_st")
h_CI_EA_low_cap_st = tf.Get("h_CI_EA_low_cap_st")
h_CI_EA_med_cap_st = tf.Get("h_CI_EA_med_cap_st")
h_CI_EA_high_cap_st = tf.Get("h_CI_EA_high_cap_st")

h_diffCorr_low_bar_st = tf.Get("h_diffCorr_low_bar_st")
h_diffCorr_med_bar_st = tf.Get("h_diffCorr_med_bar_st")
h_diffCorr_high_bar_st = tf.Get("h_diffCorr_high_bar_st")
h_diffCorr_low_cap_st = tf.Get("h_diffCorr_low_cap_st")
h_diffCorr_med_cap_st = tf.Get("h_diffCorr_med_cap_st")
h_diffCorr_high_cap_st = tf.Get("h_diffCorr_high_cap_st")

h_dB_vs_EA_low_bar_st = tf.Get("h_dB_vs_EA_low_bar_st")
h_dB_vs_EA_low_cap_st = tf.Get("h_dB_vs_EA_low_cap_st")
h_dB_vs_EA_med_bar_st = tf.Get("h_dB_vs_EA_med_bar_st")
h_dB_vs_EA_med_cap_st = tf.Get("h_dB_vs_EA_med_cap_st")
h_dB_vs_EA_high_bar_st = tf.Get("h_dB_vs_EA_high_bar_st")
h_dB_vs_EA_high_cap_st = tf.Get("h_dB_vs_EA_high_cap_st")

h_all_EAs_rel_st = tf.Get("h_all_EAs_st")

h_median_EA_rel_st = tf.Get("h_median_EA_rel_st")
h_median_dB_rel_st = tf.Get("h_median_dB_rel_st")

h_all_EAcorrs_rel_st = tf.Get("h_all_EAcorrs_rel_st")
h_all_dBcorrs_rel_st = tf.Get("h_all_dBcorrs_rel_st")

h_CIrel_dB_low_bar_st = tf.Get("h_CIrel_dB_low_bar_st")
h_CIrel_dB_med_bar_st = tf.Get("h_CIrel_dB_med_bar_st")
h_CIrel_dB_high_bar_st = tf.Get("h_CIrel_dB_high_bar_st")
h_CIrel_dB_low_cap_st = tf.Get("h_CIrel_dB_low_cap_st")
h_CIrel_dB_med_cap_st = tf.Get("h_CIrel_dB_med_cap_st")
h_CIrel_dB_high_cap_st = tf.Get("h_CIrel_dB_high_cap_st")

h_CIrel_EA_low_bar_st = tf.Get("h_CIrel_EA_low_bar_st")
h_CIrel_EA_med_bar_st = tf.Get("h_CIrel_EA_med_bar_st")
h_CIrel_EA_high_bar_st = tf.Get("h_CIrel_EA_high_bar_st")
h_CIrel_EA_low_cap_st = tf.Get("h_CIrel_EA_low_cap_st")
h_CIrel_EA_med_cap_st = tf.Get("h_CIrel_EA_med_cap_st")
h_CIrel_EA_high_cap_st = tf.Get("h_CIrel_EA_high_cap_st")

h_diffCorrRel_low_bar_st = tf.Get("h_diffCorrRel_low_bar_st")
h_diffCorrRel_med_bar_st = tf.Get("h_diffCorrRel_med_bar_st")
h_diffCorrRel_high_bar_st = tf.Get("h_diffCorrRel_high_bar_st")
h_diffCorrRel_low_cap_st = tf.Get("h_diffCorrRel_low_cap_st")
h_diffCorrRel_med_cap_st = tf.Get("h_diffCorrRel_med_cap_st")
h_diffCorrRel_high_cap_st = tf.Get("h_diffCorrRel_high_cap_st")

h_dB_vs_EA_low_bar_rel_st = tf.Get("h_dB_vs_EA_low_bar_rel_st")
h_dB_vs_EA_low_cap_rel_st = tf.Get("h_dB_vs_EA_low_cap_rel_st")
h_dB_vs_EA_med_bar_rel_st = tf.Get("h_dB_vs_EA_med_bar_rel_st")
h_dB_vs_EA_med_cap_rel_st = tf.Get("h_dB_vs_EA_med_cap_rel_st")
h_dB_vs_EA_high_bar_rel_st = tf.Get("h_dB_vs_EA_high_bar_rel_st")
h_dB_vs_EA_high_cap_rel_st = tf.Get("h_dB_vs_EA_high_cap_rel_st")

integral = int(h_all_EAs.Integral())
h_all_EAs.SetTitle("All Mini Effective Areas ("+str(integral)+" muons);Effective Area;Fraction")
h_all_EAs.Scale(1./integral)

h_median_dB.SetTitle("Median Corrections as Function of N_{PV};N_{PV};Median Absolute MiniIso Correction (GeV)")
h_median_dB.SetLineColor(ROOT.kRed)
h_median_dB.GetYaxis().SetTitleOffset(1.6)

integral = int(h_all_EAcorrs.Integral())
h_all_EAcorrs.SetTitle("All MiniIso Effective Area Corrections ("+str(integral)+" muons);Absolute Effective Area Correction (GeV);Fraction")
h_all_EAcorrs.Scale(1./integral)
integral = int(h_all_dBcorrs.Integral())
h_all_dBcorrs.SetTitle("All MiniIso #Delta#beta Corrections ("+str(integral)+" muons);Absolute #Delta#beta Correction (GeV);Fraction")
h_all_dBcorrs.Scale(1./integral)

integral = int(h_CI_dB_low_bar.Integral())
h_CI_dB_low_bar.SetTitle("#Delta#beta, |#eta| < 1.4, N_{PV} < 20 ("+str(integral)+" muons);Abs MiniIso (GeV);#Delta#beta Correction (GeV)")
integral = int(h_CI_dB_low_cap.Integral())
h_CI_dB_low_cap.SetTitle("#Delta#beta, 1.4 < |#eta| < 2.4, N_{PV} < 20 ("+str(integral)+" muons);Abs MiniIso (GeV);#Delta#beta Correction (GeV)")
integral = int(h_CI_dB_med_bar.Integral())
h_CI_dB_med_bar.SetTitle("#Delta#beta, |#eta| < 1.4, 20 <= N_{PV} < 40 ("+str(integral)+" muons);Abs MiniIso (GeV);#Delta#beta Correction (GeV)")
integral = int(h_CI_dB_med_cap.Integral())
h_CI_dB_med_cap.SetTitle("#Delta#beta, 1.4 < |#eta| < 2.4, 20 <= N_{PV} < 40 ("+str(integral)+" muons);Abs MiniIso (GeV);#Delta#beta Correction (GeV)")
integral = int(h_CI_dB_high_bar.Integral())
h_CI_dB_high_bar.SetTitle("#Delta#beta, |#eta| < 1.4, N_{PV} >= 40 ("+str(integral)+" muons);Abs MiniIso (GeV);#Delta#beta Correction (GeV)")
integral = int(h_CI_dB_high_bar.Integral())
h_CI_dB_high_cap.SetTitle("#Delta#beta, 1.4 < |#eta| < 2.4, N_{PV} >= 40 ("+str(integral)+" muons);Abs MiniIso (GeV);#Delta#beta Correction (GeV)")

integral = int(h_CI_EA_low_bar.Integral())
h_CI_EA_low_bar.SetTitle("Effective Area, |#eta| < 1.4, N_{PV} < 20 ("+str(integral)+" muons);Abs MiniIso (GeV);Effective Area Correction (GeV)")
integral = int(h_CI_EA_low_cap.Integral())
h_CI_EA_low_cap.SetTitle("Effective Area, 1.4 < |#eta| < 2.4, N_{PV} < 20 ("+str(integral)+" muons);Abs MiniIso (GeV);Effective Area Correction (GeV)")
integral = int(h_CI_EA_med_bar.Integral())
h_CI_EA_med_bar.SetTitle("Effective Area, |#eta| < 1.4, 20 <= N_{PV} < 40 ("+str(integral)+" muons);Abs MiniIso (GeV);Effective Area Correction (GeV)")
integral = int(h_CI_EA_med_cap.Integral())
h_CI_EA_med_cap.SetTitle("Effective Area, 1.4 < |#eta| < 2.4, 20 <= N_{PV} < 40 ("+str(integral)+" muons);Abs MiniIso (GeV);Effective Area Correction (GeV)")
integral = int(h_CI_EA_high_bar.Integral())
h_CI_EA_high_bar.SetTitle("Effective Area, |#eta| < 1.4, N_{PV} >= 40 ("+str(integral)+" muons);Abs MiniIso (GeV);Effective Area Correction (GeV)")
integral = int(h_CI_EA_high_bar.Integral())
h_CI_EA_high_cap.SetTitle("Effective Area, 1.4 < |#eta| < 2.4, N_{PV} >= 40 ("+str(integral)+" muons);Abs MiniIso (GeV);Effective Area Correction (GeV)")

integral = int(h_diffCorr_low_bar.Integral())
h_diffCorr_low_bar.SetTitle("MiniIso #Delta#beta - Effective Area, |#eta| < 1.4, N_{PV} < 20 ("+str(integral)+";#Delta#beta-EA (GeV);Fraction")
h_diffCorr_low_bar.Scale(1./integral)
h_diffCorr_low_bar.GetYaxis().SetTitleOffset(1.6)
integral = int(h_diffCorr_low_cap.Integral())
h_diffCorr_low_cap.SetTitle("MiniIso #Delta#beta - Effective Area, 1.4 < |#eta| < 2.4, N_{PV} < 20 ("+str(integral)+";#Delta#beta-EA (GeV);Fraction")
h_diffCorr_low_cap.Scale(1./integral)
h_diffCorr_low_cap.GetYaxis().SetTitleOffset(1.6)
integral = int(h_diffCorr_med_bar.Integral())
h_diffCorr_med_bar.SetTitle("MiniIso #Delta#beta - Effective Area, |#eta| < 1.4, 20 <= N_{PV} < 40 ("+str(integral)+";#Delta#beta-EA (GeV);Fraction")
h_diffCorr_med_bar.Scale(1./integral)
h_diffCorr_med_bar.GetYaxis().SetTitleOffset(1.6)
integral = int(h_diffCorr_med_cap.Integral())
h_diffCorr_med_cap.SetTitle("MiniIso #Delta#beta - Effective Area, 1.4 < |#eta| < 2.4, 20 <= N_{PV} < 40 ("+str(integral)+";#Delta#beta-EA (GeV);Fraction")
h_diffCorr_med_cap.Scale(1./integral)
h_diffCorr_med_cap.GetYaxis().SetTitleOffset(1.6)
integral = int(h_diffCorr_high_bar.Integral())
h_diffCorr_high_bar.SetTitle("MiniIso #Delta#beta - Effective Area, |#eta| < 1.4, N_{PV} > 40 ("+str(integral)+";#Delta#beta-EA (GeV);Fraction")
h_diffCorr_high_bar.Scale(1./integral)
h_diffCorr_high_bar.GetYaxis().SetTitleOffset(1.6)
integral = int(h_diffCorr_high_cap.Integral())
h_diffCorr_high_cap.SetTitle("MiniIso #Delta#beta - Effective Area, 1.4 < |#eta| < 2.4, N_{PV} > 40 ("+str(integral)+";#Delta#beta-EA (GeV);Fraction")
h_diffCorr_high_cap.Scale(1./integral)
h_diffCorr_high_cap.GetYaxis().SetTitleOffset(1.6)

integral = int(h_dB_vs_EA_low_bar.Integral())
h_dB_vs_EA_low_bar.SetTitle("MiniIso #Delta#beta vs Effective Area Corrections, |#eta| < 1.4, N_{PV} < 20 ("+str(integral)+" muons);Effective Area Correction (GeV);#Delta#beta Correction (GeV)")
h_dB_vs_EA_low_bar.Scale(1./integral)
integral = int(h_dB_vs_EA_low_cap.Integral())
h_dB_vs_EA_low_cap.SetTitle("MiniIso #Delta#beta vs Effective Area Corrections, 1.4 < |#eta| < 2.4, N_{PV} < 20 ("+str(integral)+" muons);Effective Area Correction (GeV);#Delta#beta Correction (GeV)")
h_dB_vs_EA_low_cap.Scale(1./integral)
integral = int(h_dB_vs_EA_med_bar.Integral())
h_dB_vs_EA_med_bar.SetTitle("MiniIso #Delta#beta vs Effective Area Corrections, |#eta| < 1.4, 20 <= N_{PV} < 40 ("+str(integral)+" muons);Effective Area Correction (GeV);#Delta#beta Correction (GeV)")
h_dB_vs_EA_med_bar.Scale(1./integral)
integral = int(h_dB_vs_EA_med_cap.Integral())
h_dB_vs_EA_med_cap.SetTitle("MiniIso #Delta#beta vs Effective Area Corrections, 1.4 < |#eta| < 2.4, 20 <= N_{PV} < 40 ("+str(integral)+" muons);Effective Area Correction (GeV);#Delta#beta Correction (GeV)")
h_dB_vs_EA_med_cap.Scale(1./integral)
integral = int(h_dB_vs_EA_high_bar.Integral())
h_dB_vs_EA_high_bar.SetTitle("MiniIso #Delta#beta vs Effective Area Corrections, |#eta| < 1.4, N_{PV} >= 40 ("+str(integral)+" muons);Effective Area Correction (GeV);#Delta#beta Correction (GeV)")
h_dB_vs_EA_high_bar.Scale(1./integral)
integral = int(h_dB_vs_EA_high_cap.Integral())
h_dB_vs_EA_high_cap.SetTitle("MiniIso #Delta#beta vs Effective Area Corrections, 1.4 < |#eta| < 2.4, N_{PV} >= 40 ("+str(integral)+" muons);Effective Area Correction (GeV);#Delta#beta Correction (GeV)")
h_dB_vs_EA_high_cap.Scale(1./integral)

# Standard

h_median_dB_st.SetTitle("Median Corrections as Function of N_{PV};N_{PV};Median Absolute #DeltaR = 0.3 Iso Correction (GeV)")
h_median_dB_st.SetLineColor(ROOT.kRed)
h_median_dB_st.GetYaxis().SetTitleOffset(1.6)

integral = int(h_all_EAcorrs_st.Integral())
h_all_EAcorrs_st.SetTitle("All #DeltaR = 0.3 Iso Effective Area Corrections ("+str(integral)+" muons);Effective Area Correction (GeV);Fraction")
h_all_EAcorrs_st.Scale(1./integral)
integral = int(h_all_dBcorrs.Integral())
h_all_dBcorrs_st.SetTitle("All #DeltaR = 0.3 Iso #Delta#beta Corrections ("+str(integral)+" muons);#Delta#beta Correction (GeV);Fraction")
h_all_dBcorrs_st.Scale(1./integral)

integral = int(h_CI_dB_low_bar_st.Integral())
h_CI_dB_low_bar_st.SetTitle("#Delta#beta, |#eta| < 1.4, N_{PV} < 20 ("+str(integral)+" muons);Abs Iso (GeV);#Delta#beta Correction (GeV)")
integral = int(h_CI_dB_low_cap_st.Integral())
h_CI_dB_low_cap_st.SetTitle("#Delta#beta, 1.4 < |#eta| < 2.4, N_{PV} < 20 ("+str(integral)+" muons);Abs Iso (GeV);#Delta#beta Correction (GeV)")
integral = int(h_CI_dB_med_bar_st.Integral())
h_CI_dB_med_bar_st.SetTitle("#Delta#beta, |#eta| < 1.4, 20 <= N_{PV} < 40 ("+str(integral)+" muons);Abs Iso (GeV);#Delta#beta Correction (GeV)")
integral = int(h_CI_dB_med_cap_st.Integral())
h_CI_dB_med_cap.SetTitle("#Delta#beta, 1.4 < |#eta| < 2.4, 20 <= N_{PV} < 40 ("+str(integral)+" muons);Abs Iso (GeV);#Delta#beta Correction (GeV)")
integral = int(h_CI_dB_high_bar_st.Integral())
h_CI_dB_high_bar_st.SetTitle("#Delta#beta, |#eta| < 1.4, N_{PV} >= 40 ("+str(integral)+" muons);Abs Iso (GeV);#Delta#beta Correction (GeV)")
integral = int(h_CI_dB_high_bar_st.Integral())
h_CI_dB_high_cap_st.SetTitle("#Delta#beta, 1.4 < |#eta| < 2.4, N_{PV} >= 40 ("+str(integral)+" muons);Abs Iso (GeV);#Delta#beta Correction (GeV)")

integral = int(h_CI_EA_low_bar_st.Integral())
h_CI_EA_low_bar_st.SetTitle("Effective Area, |#eta| < 1.4, N_{PV} < 20 ("+str(integral)+" muons);Abs Iso (GeV);Effective Area Correction (GeV)")
integral = int(h_CI_EA_low_cap_st.Integral())
h_CI_EA_low_cap_st.SetTitle("Effective Area, 1.4 < |#eta| < 2.4, N_{PV} < 20 ("+str(integral)+" muons);Abs Iso (GeV);Effective Area Correction (GeV)")
integral = int(h_CI_EA_med_bar_st.Integral())
h_CI_EA_med_bar_st.SetTitle("Effective Area, |#eta| < 1.4, 20 <= N_{PV} < 40 ("+str(integral)+" muons);Abs Iso (GeV);Effective Area Correction (GeV)")
integral = int(h_CI_EA_med_cap_st.Integral())
h_CI_EA_med_cap_st.SetTitle("Effective Area, 1.4 < |#eta| < 2.4, 20 <= N_{PV} < 40 ("+str(integral)+" muons);Abs Iso (GeV);Effective Area Correction (GeV)")
integral = int(h_CI_EA_high_bar_st.Integral())
h_CI_EA_high_bar_st.SetTitle("Effective Area, |#eta| < 1.4, N_{PV} >= 40 ("+str(integral)+" muons);Abs Iso (GeV);Effective Area Correction (GeV)")
integral = int(h_CI_EA_high_bar_st.Integral())
h_CI_EA_high_cap_st.SetTitle("Effective Area, 1.4 < |#eta| < 2.4, N_{PV} >= 40 ("+str(integral)+" muons);Abs Iso (GeV);Effective Area Correction (GeV)")

integral = int(h_diffCorr_low_bar_st.Integral())
h_diffCorr_low_bar_st.SetTitle("#DeltaR = 0.3 Iso #Delta#beta - Effective Area, |#eta| < 1.4, N_{PV} < 20 ("+str(integral)+";#Delta#beta-EA (GeV);Fraction")
h_diffCorr_low_bar_st.Scale(1./integral)
h_diffCorr_low_bar_st.GetYaxis().SetTitleOffset(1.6)
integral = int(h_diffCorr_low_cap_st.Integral())
h_diffCorr_low_cap_st.SetTitle("#DeltaR = 0.3 Iso #Delta#beta - Effective Area, 1.4 < |#eta| < 2.4, N_{PV} < 20 ("+str(integral)+";#Delta#beta-EA (GeV);Fraction")
h_diffCorr_low_cap_st.Scale(1./integral)
h_diffCorr_low_cap_st.GetYaxis().SetTitleOffset(1.6)
integral = int(h_diffCorr_med_bar_st.Integral())
h_diffCorr_med_bar_st.SetTitle("#DeltaR = 0.3 Iso #Delta#beta - Effective Area, |#eta| < 1.4, 20 <= N_{PV} < 40 ("+str(integral)+";#Delta#beta-EA (GeV);Fraction")
h_diffCorr_med_bar_st.Scale(1./integral)
h_diffCorr_med_bar_st.GetYaxis().SetTitleOffset(1.6)
integral = int(h_diffCorr_med_cap_st.Integral())
h_diffCorr_med_cap_st.SetTitle("#DeltaR = 0.3 Iso #Delta#beta - Effective Area, 1.4 < |#eta| < 2.4, 20 <= N_{PV} < 40 ("+str(integral)+";#Delta#beta-EA (GeV);Fraction")
h_diffCorr_med_cap_st.Scale(1./integral)
h_diffCorr_med_cap_st.GetYaxis().SetTitleOffset(1.6)
integral = int(h_diffCorr_high_bar_st.Integral())
h_diffCorr_high_bar_st.SetTitle("#DeltaR = 0.3 Iso #Delta#beta - Effective Area, |#eta| < 1.4, N_{PV} > 40 ("+str(integral)+";#Delta#beta-EA (GeV);Fraction")
h_diffCorr_high_bar_st.Scale(1./integral)
h_diffCorr_high_bar_st.GetYaxis().SetTitleOffset(1.6)
integral = int(h_diffCorr_high_cap_st.Integral())
h_diffCorr_high_cap_st.SetTitle("#DeltaR = 0.3 Iso #Delta#beta - Effective Area, 1.4 < |#eta| < 2.4, N_{PV} > 40 ("+str(integral)+";#Delta#beta-EA (GeV);Fraction")
h_diffCorr_high_cap_st.Scale(1./integral)
h_diffCorr_high_cap_st.GetYaxis().SetTitleOffset(1.6)

integral = int(h_dB_vs_EA_low_bar_st.Integral())
h_dB_vs_EA_low_bar_st.SetTitle("#DeltaR = 0.3 Iso #Delta#beta vs Effective Area Corrections, |#eta| < 1.4, N_{PV} < 20 ("+str(integral)+" muons);Effective Area Correction (GeV);#Delta#beta Correction (GeV)")
h_dB_vs_EA_low_bar_st.Scale(1./integral)
integral = int(h_dB_vs_EA_low_cap_st.Integral())
h_dB_vs_EA_low_cap_st.SetTitle("#DeltaR = 0.3 Iso #Delta#beta vs Effective Area Corrections, 1.4 < |#eta| < 2.4, N_{PV} < 20 ("+str(integral)+" muons);Effective Area Correction (GeV);#Delta#beta Correction (GeV)")
h_dB_vs_EA_low_cap_st.Scale(1./integral)
integral = int(h_dB_vs_EA_med_bar_st.Integral())
h_dB_vs_EA_med_bar_st.SetTitle("#DeltaR = 0.3 Iso #Delta#beta vs Effective Area Corrections, |#eta| < 1.4, 20 <= N_{PV} < 40 ("+str(integral)+" muons);Effective Area Correction (GeV);#Delta#beta Correction (GeV)")
h_dB_vs_EA_med_bar_st.Scale(1./integral)
integral = int(h_dB_vs_EA_med_cap_st.Integral())
h_dB_vs_EA_med_cap_st.SetTitle("#DeltaR = 0.3 Iso #Delta#beta vs Effective Area Corrections, 1.4 < |#eta| < 2.4, 20 <= N_{PV} < 40 ("+str(integral)+" muons);Effective Area Correction (GeV);#Delta#beta Correction (GeV)")
h_dB_vs_EA_med_cap_st.Scale(1./integral)
integral = int(h_dB_vs_EA_high_bar_st.Integral())
h_dB_vs_EA_high_bar_st.SetTitle("#DeltaR = 0.3 Iso #Delta#beta vs Effective Area Corrections, |#eta| < 1.4, N_{PV} >= 40 ("+str(integral)+" muons);Effective Area Correction (GeV);#Delta#beta Correction (GeV)")
h_dB_vs_EA_high_bar_st.Scale(1./integral)
integral = int(h_dB_vs_EA_high_cap_st.Integral())
h_dB_vs_EA_high_cap_st.SetTitle("#DeltaR = 0.3 Iso #Delta#beta vs Effective Area Corrections, 1.4 < |#eta| < 2.4, N_{PV} >= 40 ("+str(integral)+" muons);Effective Area Correction (GeV);#Delta#beta Correction (GeV)")
h_dB_vs_EA_high_cap_st.Scale(1./integral)



############
# Relative #
############


h_median_dB_rel.SetTitle("Median Corrections as Function of N_{PV};N_{PV};Median Relative MiniIso Correction")
h_median_dB_rel.SetLineColor(ROOT.kRed)
h_median_dB_rel.GetYaxis().SetTitleOffset(1.6)

integral = int(h_all_EAcorrs_rel.Integral())
h_all_EAcorrs_rel.SetTitle("All Relative MiniIso Effective Area Corrections ("+str(integral)+" muons);Effective Area Correction;Fraction")
h_all_EAcorrs_rel.Scale(1./integral)
integral = int(h_all_dBcorrs_rel.Integral())
h_all_dBcorrs_rel.SetTitle("All Relative MiniIso #Delta#beta Corrections ("+str(integral)+" muons);#Delta#beta Correction;Fraction")
h_all_dBcorrs_rel.Scale(1./integral)

integral = int(h_CIrel_dB_low_bar.Integral())
h_CIrel_dB_low_bar.SetTitle("#Delta#beta, |#eta| < 1.4, N_{PV} < 20 ("+str(integral)+" muons);Rel MiniIso;#Delta#beta Correction")
integral = int(h_CIrel_dB_low_cap.Integral())
h_CIrel_dB_low_cap.SetTitle("#Delta#beta, 1.4 < |#eta| < 2.4, N_{PV} < 20 ("+str(integral)+" muons);Rel MiniIso;#Delta#beta Correction")
integral = int(h_CIrel_dB_med_bar.Integral())
h_CIrel_dB_med_bar.SetTitle("#Delta#beta, |#eta| < 1.4, 20 <= N_{PV} < 40 ("+str(integral)+" muons);Rel MiniIso;#Delta#beta Correction")
integral = int(h_CIrel_dB_med_cap.Integral())
h_CIrel_dB_med_cap.SetTitle("#Delta#beta, 1.4 < |#eta| < 2.4, 20 <= N_{PV} < 40 ("+str(integral)+" muons);Rel MiniIso;#Delta#beta Correction")
integral = int(h_CIrel_dB_high_bar.Integral())
h_CIrel_dB_high_bar.SetTitle("#Delta#beta, |#eta| < 1.4, N_{PV} >= 40 ("+str(integral)+" muons);Rel MiniIso;#Delta#beta Correction")
integral = int(h_CIrel_dB_high_bar.Integral())
h_CIrel_dB_high_cap.SetTitle("#Delta#beta, 1.4 < |#eta| < 2.4, N_{PV} >= 40 ("+str(integral)+" muons);Rel MiniIso;#Delta#beta Correction")

integral = int(h_CIrel_EA_low_bar.Integral())
h_CIrel_EA_low_bar.SetTitle("Effective Area, |#eta| < 1.4, N_{PV} < 20 ("+str(integral)+" muons);Rel MiniIso;Effective Area Correction")
integral = int(h_CIrel_EA_low_cap.Integral())
h_CIrel_EA_low_cap.SetTitle("Effective Area, 1.4 < |#eta| < 2.4, N_{PV} < 20 ("+str(integral)+" muons);Rel MiniIso;Effective Area Correction")
integral = int(h_CIrel_EA_med_bar.Integral())
h_CIrel_EA_med_bar.SetTitle("Effective Area, |#eta| < 1.4, 20 <= N_{PV} < 40 ("+str(integral)+" muons);Rel MiniIso;Effective Area Correction")
integral = int(h_CIrel_EA_med_cap.Integral())
h_CIrel_EA_med_cap.SetTitle("Effective Area, 1.4 < |#eta| < 2.4, 20 <= N_{PV} < 40 ("+str(integral)+" muons);Rel MiniIso;Effective Area Correction")
integral = int(h_CIrel_EA_high_bar.Integral())
h_CIrel_EA_high_bar.SetTitle("Effective Area, |#eta| < 1.4, N_{PV} >= 40 ("+str(integral)+" muons);Rel MiniIso;Effective Area Correction")
integral = int(h_CIrel_EA_high_bar.Integral())
h_CIrel_EA_high_cap.SetTitle("Effective Area, 1.4 < |#eta| < 2.4, N_{PV} >= 40 ("+str(integral)+" muons);Rel MiniIso;Effective Area Correction")

integral = int(h_diffCorrRel_low_bar.Integral())
h_diffCorrRel_low_bar.SetTitle("Relative MiniIso #Delta#beta - Effective Area, |#eta| < 1.4, N_{PV} < 20 ("+str(integral)+";#Delta#beta-EA;Fraction")
h_diffCorrRel_low_bar.Scale(1./integral)
h_diffCorrRel_low_bar.GetYaxis().SetTitleOffset(1.6)
integral = int(h_diffCorrRel_low_cap.Integral())
h_diffCorrRel_low_cap.SetTitle("Relative MiniIso #Delta#beta - Effective Area, 1.4 < |#eta| < 2.4, N_{PV} < 20 ("+str(integral)+";#Delta#beta-EA;Fraction")
h_diffCorrRel_low_cap.Scale(1./integral)
h_diffCorrRel_low_cap.GetYaxis().SetTitleOffset(1.6)
integral = int(h_diffCorrRel_med_bar.Integral())
h_diffCorrRel_med_bar.SetTitle("Relative MiniIso #Delta#beta - Effective Area, |#eta| < 1.4, 20 <= N_{PV} < 40 ("+str(integral)+";#Delta#beta-EA;Fraction")
h_diffCorrRel_med_bar.Scale(1./integral)
h_diffCorrRel_med_bar.GetYaxis().SetTitleOffset(1.6)
integral = int(h_diffCorrRel_med_cap.Integral())
h_diffCorrRel_med_cap.SetTitle("Relative MiniIso #Delta#beta - Effective Area, 1.4 < |#eta| < 2.4, 20 <= N_{PV} < 40 ("+str(integral)+";#Delta#beta-EA;Fraction")
h_diffCorrRel_med_cap.Scale(1./integral)
h_diffCorrRel_med_cap.GetYaxis().SetTitleOffset(1.6)
integral = int(h_diffCorrRel_high_bar.Integral())
h_diffCorrRel_high_bar.SetTitle("Relative MiniIso #Delta#beta - Effective Area, |#eta| < 1.4, N_{PV} > 40 ("+str(integral)+";#Delta#beta-EA;Fraction")
h_diffCorrRel_high_bar.Scale(1./integral)
h_diffCorrRel_high_bar.GetYaxis().SetTitleOffset(1.6)
integral = int(h_diffCorrRel_high_cap.Integral())
h_diffCorrRel_high_cap.SetTitle("Relative MiniIso #Delta#beta - Effective Area, 1.4 < |#eta| < 2.4, N_{PV} > 40 ("+str(integral)+";#Delta#beta-EA;Fraction")
h_diffCorrRel_high_cap.Scale(1./integral)
h_diffCorrRel_high_cap.GetYaxis().SetTitleOffset(1.6)

integral = int(h_dB_vs_EA_low_bar_rel.Integral())
h_dB_vs_EA_low_bar_rel.SetTitle("Relative MiniIso #Delta#beta vs Effective Area Corrections, |#eta| < 1.4, N_{PV} < 20 ("+str(integral)+" muons);Effective Area Correction;#Delta#beta Correction")
h_dB_vs_EA_low_bar_rel.Scale(1./integral)
integral = int(h_dB_vs_EA_low_cap_rel.Integral())
h_dB_vs_EA_low_cap_rel.SetTitle("Relative MiniIso #Delta#beta vs Effective Area Corrections, 1.4 < |#eta| < 2.4, N_{PV} < 20 ("+str(integral)+" muons);Effective Area Correction;#Delta#beta Correction")
h_dB_vs_EA_low_cap_rel.Scale(1./integral)
integral = int(h_dB_vs_EA_med_bar_rel.Integral())
h_dB_vs_EA_med_bar_rel.SetTitle("Relative MiniIso #Delta#beta vs Effective Area Corrections, |#eta| < 1.4, 20 <= N_{PV} < 40 ("+str(integral)+" muons);Effective Area Correction;#Delta#beta Correction")
h_dB_vs_EA_med_bar_rel.Scale(1./integral)
integral = int(h_dB_vs_EA_med_cap_rel.Integral())
h_dB_vs_EA_med_cap_rel.SetTitle("Relative MiniIso #Delta#beta vs Effective Area Corrections, 1.4 < |#eta| < 2.4, 20 <= N_{PV} < 40 ("+str(integral)+" muons);Effective Area Correction;#Delta#beta Correction")
h_dB_vs_EA_med_cap_rel.Scale(1./integral)
integral = int(h_dB_vs_EA_high_bar_rel.Integral())
h_dB_vs_EA_high_bar_rel.SetTitle("Relative MiniIso #Delta#beta vs Effective Area Corrections, |#eta| < 1.4, N_{PV} >= 40 ("+str(integral)+" muons);Effective Area Correction;#Delta#beta Correction")
h_dB_vs_EA_high_bar_rel.Scale(1./integral)
integral = int(h_dB_vs_EA_high_cap_rel.Integral())
h_dB_vs_EA_high_cap_rel.SetTitle("Relative MiniIso #Delta#beta vs Effective Area Corrections, 1.4 < |#eta| < 2.4, N_{PV} >= 40 ("+str(integral)+" muons);Effective Area Correction;#Delta#beta Correction")
h_dB_vs_EA_high_cap_rel.Scale(1./integral)

# Standard

h_median_dB_rel_st.SetTitle("Median Corrections as Function of N_{PV};N_{PV};Median Relative #DeltaR = 0.3 Iso Correction")
h_median_dB_rel_st.SetLineColor(ROOT.kRed)
h_median_dB_rel_st.GetYaxis().SetTitleOffset(1.6)

integral = int(h_all_EAcorrs_rel_st.Integral())
h_all_EAcorrs_rel_st.SetTitle("All #DeltaR = 0.3 Iso Effective Area Corrections ("+str(integral)+" muons);Effective Area Correction;Fraction")
h_all_EAcorrs_rel_st.Scale(1./integral)
integral = int(h_all_dBcorrs_rel_st.Integral())
h_all_dBcorrs_rel_st.SetTitle("All #DeltaR = 0.3 Iso #Delta#beta Corrections ("+str(integral)+" muons);#Delta#beta Correction;Fraction")
h_all_dBcorrs_rel_st.Scale(1./integral)

integral = int(h_CIrel_dB_low_bar_st.Integral())
h_CIrel_dB_low_bar_st.SetTitle("#Delta#beta, |#eta| < 1.4, N_{PV} < 20 ("+str(integral)+" muons);Rel Iso;#Delta#beta Correction")
integral = int(h_CIrel_dB_low_cap_st.Integral())
h_CIrel_dB_low_cap_st.SetTitle("#Delta#beta, 1.4 < |#eta| < 2.4, N_{PV} < 20 ("+str(integral)+" muons);Rel Iso;#Delta#beta Correction")
integral = int(h_CIrel_dB_med_bar_st.Integral())
h_CIrel_dB_med_bar_st.SetTitle("#Delta#beta, |#eta| < 1.4, 20 <= N_{PV} < 40 ("+str(integral)+" muons);Rel Iso;#Delta#beta Correction")
integral = int(h_CIrel_dB_med_cap_st.Integral())
h_CIrel_dB_med_cap.SetTitle("#Delta#beta, 1.4 < |#eta| < 2.4, 20 <= N_{PV} < 40 ("+str(integral)+" muons);Rel Iso;#Delta#beta Correction")
integral = int(h_CIrel_dB_high_bar_st.Integral())
h_CIrel_dB_high_bar_st.SetTitle("#Delta#beta, |#eta| < 1.4, N_{PV} >= 40 ("+str(integral)+" muons);Rel Iso;#Delta#beta Correction")
integral = int(h_CIrel_dB_high_bar_st.Integral())
h_CIrel_dB_high_cap_st.SetTitle("#Delta#beta, 1.4 < |#eta| < 2.4, N_{PV} >= 40 ("+str(integral)+" muons);Rel Iso;#Delta#beta Correction")

integral = int(h_CIrel_EA_low_bar_st.Integral())
h_CIrel_EA_low_bar_st.SetTitle("Effective Area, |#eta| < 1.4, N_{PV} < 20 ("+str(integral)+" muons);Rel Iso;Effective Area Correction")
integral = int(h_CIrel_EA_low_cap_st.Integral())
h_CIrel_EA_low_cap_st.SetTitle("Effective Area, 1.4 < |#eta| < 2.4, N_{PV} < 20 ("+str(integral)+" muons);Rel Iso;Effective Area Correction")
integral = int(h_CIrel_EA_med_bar_st.Integral())
h_CIrel_EA_med_bar_st.SetTitle("Effective Area, |#eta| < 1.4, 20 <= N_{PV} < 40 ("+str(integral)+" muons);Rel Iso;Effective Area Correction")
integral = int(h_CIrel_EA_med_cap_st.Integral())
h_CIrel_EA_med_cap_st.SetTitle("Effective Area, 1.4 < |#eta| < 2.4, 20 <= N_{PV} < 40 ("+str(integral)+" muons);Rel Iso;Effective Area Correction")
integral = int(h_CIrel_EA_high_bar_st.Integral())
h_CIrel_EA_high_bar_st.SetTitle("Effective Area, |#eta| < 1.4, N_{PV} >= 40 ("+str(integral)+" muons);Rel Iso;Effective Area Correction")
integral = int(h_CIrel_EA_high_bar_st.Integral())
h_CIrel_EA_high_cap_st.SetTitle("Effective Area, 1.4 < |#eta| < 2.4, N_{PV} >= 40 ("+str(integral)+" muons);Rel Iso;Effective Area Correction")

integral = int(h_diffCorrRel_low_bar_st.Integral())
h_diffCorrRel_low_bar_st.SetTitle("#DeltaR = 0.3 Iso #Delta#beta - Effective Area, |#eta| < 1.4, N_{PV} < 20 ("+str(integral)+";#Delta#beta-EA;Fraction")
h_diffCorrRel_low_bar_st.Scale(1./integral)
h_diffCorrRel_low_bar_st.GetYaxis().SetTitleOffset(1.6)
integral = int(h_diffCorrRel_low_cap_st.Integral())
h_diffCorrRel_low_cap_st.SetTitle("#DeltaR = 0.3 Iso #Delta#beta - Effective Area, 1.4 < |#eta| < 2.4, N_{PV} < 20 ("+str(integral)+";#Delta#beta-EA;Fraction")
h_diffCorrRel_low_cap_st.Scale(1./integral)
h_diffCorrRel_low_cap_st.GetYaxis().SetTitleOffset(1.6)
integral = int(h_diffCorrRel_med_bar_st.Integral())
h_diffCorrRel_med_bar_st.SetTitle("#DeltaR = 0.3 Iso #Delta#beta - Effective Area, |#eta| < 1.4, 20 <= N_{PV} < 40 ("+str(integral)+";#Delta#beta-EA;Fraction")
h_diffCorrRel_med_bar_st.Scale(1./integral)
h_diffCorrRel_med_bar_st.GetYaxis().SetTitleOffset(1.6)
integral = int(h_diffCorrRel_med_cap_st.Integral())
h_diffCorrRel_med_cap_st.SetTitle("#DeltaR = 0.3 Iso #Delta#beta - Effective Area, 1.4 < |#eta| < 2.4, 20 <= N_{PV} < 40 ("+str(integral)+";#Delta#beta-EA;Fraction")
h_diffCorrRel_med_cap_st.Scale(1./integral)
h_diffCorrRel_med_cap_st.GetYaxis().SetTitleOffset(1.6)
integral = int(h_diffCorrRel_high_bar_st.Integral())
h_diffCorrRel_high_bar_st.SetTitle("#DeltaR = 0.3 Iso #Delta#beta - Effective Area, |#eta| < 1.4, N_{PV} > 40 ("+str(integral)+";#Delta#beta-EA;Fraction")
h_diffCorrRel_high_bar_st.Scale(1./integral)
h_diffCorrRel_high_bar_st.GetYaxis().SetTitleOffset(1.6)
integral = int(h_diffCorrRel_high_cap_st.Integral())
h_diffCorrRel_high_cap_st.SetTitle("#DeltaR = 0.3 Iso #Delta#beta - Effective Area, 1.4 < |#eta| < 2.4, N_{PV} > 40 ("+str(integral)+";#Delta#beta-EA;Fraction")
h_diffCorrRel_high_cap_st.Scale(1./integral)
h_diffCorrRel_high_cap_st.GetYaxis().SetTitleOffset(1.6)

integral = int(h_dB_vs_EA_low_bar_rel_st.Integral())
h_dB_vs_EA_low_bar_rel_st.SetTitle("Relative #DeltaR = 0.3 Iso #Delta#beta vs Effective Area Corrections, |#eta| < 1.4, N_{PV} < 20 ("+str(integral)+" muons);Effective Area Correction;#Delta#beta Correction")
h_dB_vs_EA_low_bar_rel_st.Scale(1./integral)
integral = int(h_dB_vs_EA_low_cap_rel_st.Integral())
h_dB_vs_EA_low_cap_rel_st.SetTitle("Relative #DeltaR = 0.3 Iso #Delta#beta vs Effective Area Corrections, 1.4 < |#eta| < 2.4, N_{PV} < 20 ("+str(integral)+" muons);Effective Area Correction;#Delta#beta Correction")
h_dB_vs_EA_low_cap_rel_st.Scale(1./integral)
integral = int(h_dB_vs_EA_med_bar_rel_st.Integral())
h_dB_vs_EA_med_bar_rel_st.SetTitle("Relative #DeltaR = 0.3 Iso #Delta#beta vs Effective Area Corrections, |#eta| < 1.4, 20 <= N_{PV} < 40 ("+str(integral)+" muons);Effective Area Correction;#Delta#beta Correction")
h_dB_vs_EA_med_bar_rel_st.Scale(1./integral)
integral = int(h_dB_vs_EA_med_cap_rel_st.Integral())
h_dB_vs_EA_med_cap_rel_st.SetTitle("Relative #DeltaR = 0.3 Iso #Delta#beta vs Effective Area Corrections, 1.4 < |#eta| < 2.4, 20 <= N_{PV} < 40 ("+str(integral)+" muons);Effective Area Correction;#Delta#beta Correction")
h_dB_vs_EA_med_cap_rel_st.Scale(1./integral)
integral = int(h_dB_vs_EA_high_bar_rel_st.Integral())
h_dB_vs_EA_high_bar_rel_st.SetTitle("Relative #DeltaR = 0.3 Iso #Delta#beta vs Effective Area Corrections, |#eta| < 1.4, N_{PV} >= 40 ("+str(integral)+" muons);Effective Area Correction;#Delta#beta Correction")
h_dB_vs_EA_high_bar_rel_st.Scale(1./integral)
integral = int(h_dB_vs_EA_high_cap_rel_st.Integral())
h_dB_vs_EA_high_cap_rel_st.SetTitle("Relative #DeltaR = 0.3 Iso #Delta#beta vs Effective Area Corrections, 1.4 < |#eta| < 2.4, N_{PV} >= 40 ("+str(integral)+" muons);Effective Area Correction;#Delta#beta Correction")
h_dB_vs_EA_high_cap_rel_st.Scale(1./integral)



#################

##############
# Make Plots #
##############

#################

canvas = ROOT.TCanvas()
canvas.SetCanvasSize(700,700)
pads = [canvas]
pads[0].SetLeftMargin(0.12)
pads[0].SetTopMargin(0.12)
pads[0].SetRightMargin(0.12)
pads[0].cd()

x = n.linspace(0,100,5)
y = x
tg = ROOT.TGraph(2,x,y);
tg.SetLineWidth(3)

tl = ROOT.TLegend(0.20,0.75,0.40,0.85)
tl.AddEntry(h_median_dB,"Median #Delta#beta")
tl.AddEntry(h_median_EA,"Median Effective Area")
h_median_dB.Draw()
h_median_EA.Draw("same")
tl.Draw()
canvas.SaveAs("PNGs/median_corrs.png")

canvas.SetLogy(True)
canvas.SetLogz(True)

h_all_EAcorrs.Draw()
canvas.SaveAs("PNGs/all_EAcorrs.png")
h_all_dBcorrs.Draw()
canvas.SaveAs("PNGs/all_dBcorrs.png")
canvas.SetLogx(True)

h_CI_dB_low_bar.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/dB_low_bar.png")
h_CI_dB_low_cap.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/dB_low_cap.png")
h_CI_dB_med_bar.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/dB_med_bar.png")
h_CI_dB_med_cap.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/dB_med_cap.png")
h_CI_dB_high_bar.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/dB_high_bar.png")
h_CI_dB_high_cap.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/dB_high_cap.png")

h_CI_EA_low_bar.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/EA_low_bar.png")
h_CI_EA_low_cap.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/EA_low_cap.png")
h_CI_EA_med_bar.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/EA_med_bar.png")
h_CI_EA_med_cap.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/EA_med_cap.png")
h_CI_EA_high_bar.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/EA_high_bar.png")
h_CI_EA_high_cap.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/EA_high_cap.png")

canvas.SetLogx(False)
h_diffCorr_low_bar.Draw("hist")
canvas.SaveAs("PNGs/diffCorr_low_bar.png")
h_diffCorr_low_cap.Draw("hist")
canvas.SaveAs("PNGs/diffCorr_low_cap.png")
h_diffCorr_med_bar.Draw("hist")
canvas.SaveAs("PNGs/diffCorr_med_bar.png")
h_diffCorr_med_cap.Draw("hist")
canvas.SaveAs("PNGs/diffCorr_med_cap.png")
h_diffCorr_high_bar.Draw("hist")
canvas.SaveAs("PNGs/diffCorr_high_bar.png")
h_diffCorr_high_cap.Draw("hist")
canvas.SaveAs("PNGs/diffCorr_high_cap.png")
canvas.SetLogx(True)

h_dB_vs_EA_low_bar.Draw("colz")
canvas.SaveAs("PNGs/dB_vs_EA_low_bar.png")
h_dB_vs_EA_low_cap.Draw("colz")
canvas.SaveAs("PNGs/dB_vs_EA_low_cap.png")
h_dB_vs_EA_med_bar.Draw("colz")
canvas.SaveAs("PNGs/dB_vs_EA_med_bar.png")
h_dB_vs_EA_med_cap.Draw("colz")
canvas.SaveAs("PNGs/dB_vs_EA_med_cap.png")
h_dB_vs_EA_high_bar.Draw("colz")
canvas.SaveAs("PNGs/dB_vs_EA_high_bar.png")
h_dB_vs_EA_high_cap.Draw("colz")
canvas.SaveAs("PNGs/dB_vs_EA_high_cap.png")

#Relative 

canvas.SetLogx(False)
canvas.SetLogy(False)
tl.Clear()
tl.AddEntry(h_median_dB_rel,"Median #Delta#beta")
tl.AddEntry(h_median_EA_rel,"Median Effective Area")
h_median_dB_rel.Draw()
h_median_EA_rel.Draw("same")
tl.Draw()
canvas.SaveAs("PNGs/median_corrs_rel.png")
canvas.SetLogy(True)

h_all_EAcorrs_rel.Draw("hist")
canvas.SaveAs("PNGs/all_EAcorrs_rel.png")
h_all_dBcorrs_rel.Draw("hist")
canvas.SaveAs("PNGs/all_dBcorrs_rel.png")
canvas.SetLogx(True)

h_CIrel_dB_low_bar.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/dB_low_bar_rel.png")
h_CIrel_dB_low_cap.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/dB_low_cap_rel.png")
h_CIrel_dB_med_bar.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/dB_med_bar_rel.png")
h_CIrel_dB_med_cap.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/dB_med_cap_rel.png")
h_CIrel_dB_high_bar.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/dB_high_bar_rel.png")
h_CIrel_dB_high_cap.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/dB_high_cap_rel.png")

h_CIrel_EA_low_bar.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/EA_low_bar_rel.png")
h_CIrel_EA_low_cap.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/EA_low_cap_rel.png")
h_CIrel_EA_med_bar.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/EA_med_bar_rel.png")
h_CIrel_EA_med_cap.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/EA_med_cap_rel.png")
h_CIrel_EA_high_bar.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/EA_high_bar_rel.png")
h_CIrel_EA_high_cap.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/EA_high_cap_rel.png")

canvas.SetLogx(False)
h_diffCorrRel_low_bar.Draw("hist")
canvas.SaveAs("PNGs/diffCorrRel_low_bar.png")
h_diffCorrRel_low_cap.Draw("hist")
canvas.SaveAs("PNGs/diffCorrRel_low_cap.png")
h_diffCorrRel_med_bar.Draw("hist")
canvas.SaveAs("PNGs/diffCorrRel_med_bar.png")
h_diffCorrRel_med_cap.Draw("hist")
canvas.SaveAs("PNGs/diffCorrRel_med_cap.png")
h_diffCorrRel_high_bar.Draw("hist")
canvas.SaveAs("PNGs/diffCorrRel_high_bar.png")
h_diffCorrRel_high_cap.Draw("hist")
canvas.SaveAs("PNGs/diffCorrRel_high_cap.png")
canvas.SetLogx(True)

h_dB_vs_EA_low_bar_rel.Draw("colz")
canvas.SaveAs("PNGs/dB_vs_EA_low_bar_rel.png")
h_dB_vs_EA_low_cap_rel.Draw("colz")
canvas.SaveAs("PNGs/dB_vs_EA_low_cap_rel.png")
h_dB_vs_EA_med_bar_rel.Draw("colz")
canvas.SaveAs("PNGs/dB_vs_EA_med_bar_rel.png")
h_dB_vs_EA_med_cap_rel.Draw("colz")
canvas.SaveAs("PNGs/dB_vs_EA_med_cap_rel.png")
h_dB_vs_EA_high_bar_rel.Draw("colz")
canvas.SaveAs("PNGs/dB_vs_EA_high_bar_rel.png")
h_dB_vs_EA_high_cap_rel.Draw("colz")
canvas.SaveAs("PNGs/dB_vs_EA_high_cap_rel.png")

############
# Standard #
############

canvas.SetLogx(False)
canvas.SetLogy(False)
tl.Clear()
tl.AddEntry(h_median_dB_st,"Median #Delta#beta")
tl.AddEntry(h_median_EA_st,"Median Effective Area")
h_median_dB_st.Draw()
h_median_EA_st.Draw("same")
tl.Draw()
canvas.SaveAs("PNGs/median_corrs_st.png")
canvas.SetLogy(True)

h_all_EAcorrs_st.Draw()
canvas.SaveAs("PNGs/all_EAcorrs_st.png")
h_all_dBcorrs_st.Draw()
canvas.SaveAs("PNGs/all_dBcorrs_st.png")
canvas.SetLogx(True)

h_CI_dB_low_bar_st.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/dB_low_bar_st.png")
h_CI_dB_low_cap_st.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/dB_low_cap_st.png")
h_CI_dB_med_bar_st.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/dB_med_bar_st.png")
h_CI_dB_med_cap_st.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/dB_med_cap_st.png")
h_CI_dB_high_bar_st.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/dB_high_bar_st.png")
h_CI_dB_high_cap_st.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/dB_high_cap_st.png")

h_CI_EA_low_bar_st.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/EA_low_bar_st.png")
h_CI_EA_low_cap_st.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/EA_low_cap_st.png")
h_CI_EA_med_bar_st.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/EA_med_bar_st.png")
h_CI_EA_med_cap_st.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/EA_med_cap_st.png")
h_CI_EA_high_bar_st.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/EA_high_bar_st.png")
h_CI_EA_high_cap_st.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/EA_high_cap_st.png")

canvas.SetLogx(False)
h_diffCorr_low_bar_st.Draw("hist")
canvas.SaveAs("PNGs/diffCorr_low_bar_st.png")
h_diffCorr_low_cap.Draw("hist")
canvas.SaveAs("PNGs/diffCorr_low_cap_st.png")
h_diffCorr_med_bar_st.Draw("hist")
canvas.SaveAs("PNGs/diffCorr_med_bar_st.png")
h_diffCorr_med_cap.Draw("hist")
canvas.SaveAs("PNGs/diffCorr_med_cap_st.png")
h_diffCorr_high_bar_st.Draw("hist")
canvas.SaveAs("PNGs/diffCorr_high_bar_st.png")
h_diffCorr_high_cap.Draw("hist")
canvas.SaveAs("PNGs/diffCorr_high_cap_st.png")
canvas.SetLogx(True)

h_dB_vs_EA_low_bar_st.Draw("colz")
canvas.SaveAs("PNGs/dB_vs_EA_low_bar_st.png")
h_dB_vs_EA_low_cap_st.Draw("colz")
canvas.SaveAs("PNGs/dB_vs_EA_low_cap_st.png")
h_dB_vs_EA_med_bar_st.Draw("colz")
canvas.SaveAs("PNGs/dB_vs_EA_med_bar_st.png")
h_dB_vs_EA_med_cap_st.Draw("colz")
canvas.SaveAs("PNGs/dB_vs_EA_med_cap_st.png")
h_dB_vs_EA_high_bar_st.Draw("colz")
canvas.SaveAs("PNGs/dB_vs_EA_high_bar_st.png")
h_dB_vs_EA_high_cap_st.Draw("colz")
canvas.SaveAs("PNGs/dB_vs_EA_high_cap_st.png")

#Relative 

canvas.SetLogx(False)
canvas.SetLogy(False)
tl.Clear()
tl.AddEntry(h_median_dB_rel_st,"Median #Delta#beta")
tl.AddEntry(h_median_EA_rel_st,"Median Effective Area")
h_median_dB_rel_st.Draw()
h_median_EA_rel_st.Draw("same")
tl.Draw()
canvas.SaveAs("PNGs/median_corrs_rel_st.png")
canvas.SetLogy(True)

h_all_EAcorrs_rel_st.Draw("hist")
canvas.SaveAs("PNGs/all_EAcorrs_rel_st.png")
h_all_dBcorrs_rel_st.Draw("hist")
canvas.SaveAs("PNGs/all_dBcorrs_rel_st.png")
canvas.SetLogx(True)

h_CIrel_dB_low_bar_st.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/dB_low_bar_rel_st.png")
h_CIrel_dB_low_cap_st.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/dB_low_cap_rel_st.png")
h_CIrel_dB_med_bar_st.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/dB_med_bar_rel_st.png")
h_CIrel_dB_med_cap_st.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/dB_med_cap_rel_st.png")
h_CIrel_dB_high_bar_st.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/dB_high_bar_rel_st.png")
h_CIrel_dB_high_cap_st.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/dB_high_cap_rel_st.png")

h_CIrel_EA_low_bar_st.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/EA_low_bar_rel_st.png")
h_CIrel_EA_low_cap_st.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/EA_low_cap_rel_st.png")
h_CIrel_EA_med_bar_st.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/EA_med_bar_rel_st.png")
h_CIrel_EA_med_cap_st.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/EA_med_cap_rel_st.png")
h_CIrel_EA_high_bar_st.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/EA_high_bar_rel_st.png")
h_CIrel_EA_high_cap_st.Draw("colz")
tg.Draw("same")
canvas.SaveAs("PNGs/EA_high_cap_rel_st.png")

canvas.SetLogx(False)
h_diffCorrRel_low_bar_st.Draw("hist")
canvas.SaveAs("PNGs/diffCorrRel_low_bar_st.png")
h_diffCorrRel_low_cap_st.Draw("hist")
canvas.SaveAs("PNGs/diffCorrRel_low_cap_st.png")
h_diffCorrRel_med_bar_st.Draw("hist")
canvas.SaveAs("PNGs/diffCorrRel_med_bar_st.png")
h_diffCorrRel_med_cap_st.Draw("hist")
canvas.SaveAs("PNGs/diffCorrRel_med_cap_st.png")
h_diffCorrRel_high_bar_st.Draw("hist")
canvas.SaveAs("PNGs/diffCorrRel_high_bar_st.png")
h_diffCorrRel_high_cap_st.Draw("hist")
canvas.SaveAs("PNGs/diffCorrRel_high_cap_st.png")
canvas.SetLogx(True)

h_dB_vs_EA_low_bar_rel_st.Draw("colz")
canvas.SaveAs("PNGs/dB_vs_EA_low_bar_rel_st.png")
h_dB_vs_EA_low_cap_rel_st.Draw("colz")
canvas.SaveAs("PNGs/dB_vs_EA_low_cap_rel_st.png")
h_dB_vs_EA_med_bar_rel_st.Draw("colz")
canvas.SaveAs("PNGs/dB_vs_EA_med_bar_rel_st.png")
h_dB_vs_EA_med_cap_rel_st.Draw("colz")
canvas.SaveAs("PNGs/dB_vs_EA_med_cap_rel_st.png")
h_dB_vs_EA_high_bar_rel_st.Draw("colz")
canvas.SaveAs("PNGs/dB_vs_EA_high_bar_rel_st.png")
h_dB_vs_EA_high_cap_rel_st.Draw("colz")
canvas.SaveAs("PNGs/dB_vs_EA_high_cap_rel_st.png")
